src/machine.tex, src/priv-instr-table.tex
=> Describe ECALL/EBREAK operation in privileged architecture

src/hypervisor.tex, src/machine.tex, src/priv-csrs.tex, src/priv-preface.tex, src/supervisor.tex
=> Resolve ambiguities for CSRs due to configurable XLENs

src/history.tex, src/riscv-spec.tex
Somehow I lost these two names in the middle of the alphabet...
my apologies!
=> Add Luc and Yatin as memory model contributors

src/graphviz/litmus_addrpo.dot, src/graphviz/litmus_datacoirfi.dot, src/graphviz/litmus_datarfi.dot, src/graphviz/litmus_lb_lrsc.dot, src/graphviz/litmus_mp_fenceww_fri_rfi_addr.dot, src/graphviz/litmus_ppoca.dot, src/graphviz/litmus_rsw.dot, src/graphviz/litmus_sample.dot, src/graphviz/litmus_sb_fwd.dot, src/graphviz/litmus_subsumption.dot
Those sources (.dot) are to be processed by neato.
=> Add graphviz sources of figures from the "RVWMO Explanatory Material" appendix.

src/f.tex
=> Clarified description of fused multiply-add instructions.

src/a.tex, src/c.tex, src/intro.tex, src/memory.tex, src/rv32.tex, src/rvwmo.tex
I just finished reading through the ISA manual and found several minor spelling/grammar/formatting issues, which I've addressed in these commits.
=> Miscellaneous spelling/grammar/formatting fixes

src/assembly.tex, src/c.tex, src/rv32.tex
=> Make JALR assembly format consistent with binutils

src/memory-model-operational.tex
To be reviewed by @daniellustig
=> Minor change to the operational memory model

marchid.md
=> Register YARVI's machid

src/memory-model-operational.tex
=> Fix minor typos in the operational model.

src/machine.tex
=> Define semantics for contradictory misa settings

src/a.tex
=> Clarify behavior of LR.rl and SC.aq

src/machine.tex
=> Minor grammar fix

src/a.tex
Address argument was clobbered.
Signed-off-by: David Horner <ds2horner@gmail.com>
=> Correct iteration in LR/SC CAS example.

src/machine.tex, src/priv-csrs.tex, src/priv-preface.tex, src/supervisor.tex
=> Add endianness control proposal to priv spec

src/intro.tex, src/machine.tex, src/preamble.tex, src/rv32.tex, src/supervisor.tex
Here are my proposed changes in support of https://github.com/riscv/riscv-isa-manual/issues/377.
Note that many more things would presumably fall into this UNSPECIFIED category but this pull request contains the basic definition and a few concrete examples.  Documenting other behaviors and values as UNSPECIFIED can be done later as necessary.
=> Proposal to explicitly declare things as UNSPECIFIED

marchid.md
Western Digital's second generation cores SweRV EL2 and EH2
=> Add Western Digital's SweRV EL2 and EH2 cores

src/c.tex
=> Non misleading bit width expression in chapter C

src/instr-table.tex
Signed-off-by: Chih-Min Chao <chihmin.chao@sifive.com>
=> zfh: add encoding table

src/instr-table.tex, src/zfh.tex
Signed-off-by: Chih-Min Chao <cmchao@gmail.com>
=> zfh: add missing encoding table for fmv

marchid.md
This Pull Request updates the cores that are now part of openhw group,  previously under the pulp project
=> update OpenHW cores

src/priv-intro.tex
=> Require unimplemented instructions to trap

src/f.tex
=> Clarify rm field on widening conversions

marchid.md
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>
=> Requesting marchid for cv32e40x and cv32e40s

marchid.md
Please allocate a marchid for the [RudolV](https://github.com/bobbl/rudolv) processor
=> marchid request for RudolV

marchid.md
Hi,
I just added a marchid for Steel Core (github.com/rafaelcalcada/steel-core).
=> Adding Steel Core marchid

src/csr.tex, src/priv-csrs.tex
No normative change to existing standards in this PR.
=> Standard CSRs don't have read side effects

src/memory.tex
Thanks to @YenHaoChen.
Closes #731
=> Fix a typo in Figure A.13.

src/hypervisor.tex, src/machine.tex, src/priv-instr-table.tex, src/priv-preface.tex, src/supervisor.tex
Svnapot, Svpbmt, and Svinval.
This PR replaces #628, #663, and #668.  The content is the same, except that:
* public review feedback has been incorporated
* the content has been rebased onto the latest state of the master branch
=> Virtual memory task group extensions

.github/workflows/build-pdf.yml
Add GitHub workflow for building the Asciidoc Unprivileged ISA pdf.
Signed-off-by: Stephano Cetola <scetola@linuxfoundation.org>
=> Add yaml file for build automation

src/preface.tex, src/riscv-spec.tex, src/zihintntl.tex, src/zihintntlh.tex
Non-temporal locality hints.  See text.
=> Add Zihintntl spec

src/counters.tex
Clarifications to chapter for ratification.
=> Zicntr zihpm ratification

marchid.md
Signed-off-by: Ruige Lee <295054118@whut.edu.cn>
=> Add marchid for Rift

marchid.md
Signed-off-by: stnolting-ims <117631738+stnolting-ims@users.noreply.github.com>
Signed-off-by: stnolting-ims <117631738+stnolting-ims@users.noreply.github.com>
=> Add marchid for Fraunhofer-IMS AIRISC (#913)

src/riscv-isa-unpr-conv-review.adoc
Fixed accents in Krste's last name.
Fixed accent in Rimas' last name.
=> Fixing accents in names.

src/rv32.adoc
Cleaning up backticks that converted wrong.
=> Cleaned up backticks.

build/Makefile
Switching back to build unpriv
=> Switching back to build unpriv

.github/workflows/build-pdf.yml
Added back build-pdf.yml in order to be able to
trigger it from actions.
=> Adding back build-pdf.yml

src/resources/themes/riscv-spec.yml
Added Droid Fallback fonts explicitly
=> Added Droid Fallback fonts explicitly

src/hypervisor.tex, src/machine.tex
Resolves #961.
See discusson on that issue for motivation.
=> Clarify WFI trapping behavior

src/memory.tex
fixes #795
Fixes are as suggested there by several contributors.
=> Fix Known Issues examples

marchid.md
=> Add marchid for VexRiscv

src/hypervisor.adoc, src/images/bytefield/mseccfg.adoc, src/machine.adoc, src/priv-csrs.adoc, src/priv-preface.adoc
=> Clarify behavior of explicit accesses to CSRs wider than XLEN

src/images/bytefield/rv32satp.edn
=> fix satp.asid width

build/.gitignore
... to exclude those files:
*   `build/priv-isa-asciidoc.html`
*   `build/unpriv-isa-asciidoc.html`
=> Add `*.html` to `build/.gitignore`

src/supervisor.adoc
=> Add missing words

src/machine.adoc, src/supervisor.adoc
Fix extra space for xIE, add missing word for number of ASID bits etc
=> Fix typo and missing 

marchid.md
Allocation request to add marchid 40 for ApogeoRV CPU
=> Add marchid for ApogeoRV

marchid.md
marchid allocation request for MircoRV32
=> Add marchid for MicroRV32

src/mm-alloy.adoc
=> fix broken alloy link

src/machine.adoc, src/priv-csrs.adoc, src/priv-preface.adoc
Resolves #1203 (that is, if we choose to resolve it in this manner).
=> Redefine MXL to be read-only

src/supervisor.adoc
These clarifications were created as part of the Svadu extension development.
=> Clarifications to the Addressing and Memory Protection section

src/counters.adoc
Text contributed by @gfavor.
@kasanovic This corresponds to the conclusion of an ARC meeting several months ago, but I thought you'd like the chance to weigh in before we merge this one.
Resolves #1113
=> Add clarifying non-normative comments about [m]time

src/counters.adoc, src/machine.adoc
Heterogeneous systems can have different privilege mode support in different harts, can have different XLEN support in different harts, etc.
=> Don't conflate hart and system

src/riscv-privileged.adoc, src/sscofpmt.adoc
Added sscofpmf.adoc file and included in priv spec. Updated referenced figures to the asciidoc versions.
=> Adding Sscofpmf to priv spec.

src/zicsr.adoc
See https://lists.riscv.org/g/tech-unprivileged/message/717
=> Clarify behavior of CSR access side effects

src/riscv-privileged.adoc, src/smcntrpmf.adoc
Integrate the Smcntrpmf chapter into the Privileged spec.
=> Smcntrpmf chapter integration.

src/indirect-csr.adoc, src/riscv-privileged.adoc
Integration of the "Smcsrind/Sscsrind" sepc into the Privileged spec.
=> Indirect-csr integration into privileged spec.

src/machine.adoc
Moving change from latex to adoc.
If this change is not required or recommended, please close the PR.
=> Updating machine.adoc based on older PR

src/smstateen.adoc
Adding Ssstateen to chapter and adding paragraph to Proposal section.
=> Adding Ssstateen to chapter.

src/b-st-ext.adoc
Updates per issue - https://github.com/riscv/riscv-isa-manual/issues/1282
=> Reordering

src/resources/themes/riscv-spec.yml
Commented out the font-size: 11.5 in the codespan section.  Fixes issue #1322
=> Removing font-size setting of 11.5 on codespan.

src/supervisor.adoc
Spec: https://github.com/riscv/riscv-svvptc
=> Integrate Svvptc standard extension

src/priv-csrs.adoc, src/smstateen.adoc, src/supervisor.adoc
spec: https://github.com/riscv/riscv-ssqosid
=> Integrate ssqosid extension

src/smstateen.adoc, src/zc.adoc
=> Use lower case for jvt  CSR name

src/a-st-ext.adoc, src/zacas.adoc, src/zawrs.adoc
Spec: https://github.com/riscv/riscv-zaamo-zalrsc
Status: Frozen
=> Integrate Zaamo and Zalrsc text

src/mm-eplan.adoc
Updates from old PR - https://github.com/riscv/riscv-isa-manual/pull/529/files
Note that some of these changes already made their way into the adoc file. So if these changes are not needed, close the PR.
=> Old PR - Add initial value of Figure A.13

src/supervisor.adoc
https://github.com/riscv/riscv-isa-manual/issues/1370
=> page fault vs page-fault

src/naming.adoc
Fixed some problems mentioned in #1390
=> Clarify the ordering of Additional Standard Unprivileged Extensions

src/b-st-ext.adoc, src/scalar-crypto.adoc
Several places where extensions were marked as frozen when they were actually ratified.
=> Fixing instances of "frozen".

src/intro.adoc
Minor correction to grammar in the intro section.
=> Minor correction to grammar

build/Makefile
No need for asciidoc in filenames therefore removing.
=> Remove word asciidoc from generated file names

.github/workflows/isa-build.yml, .github/workflows/merge-and-release.yml
Updated the filenames in the GH workflows.
=> Update filenames in workflows.

src/b-st-ext.adoc, src/cmo.adoc, src/scalar-crypto.adoc
=> Duplicate IDs

.github/workflows/merge-and-release.yml
=> Update path to build dir

.github/workflows/merge-and-release.yml
Reverts riscv/riscv-isa-manual#1455
=> Revert "Update path to build dir"

Makefile
This adds specific build targets for PDF, EPUB, or HTML.
=> Add build targets for PDF, EPUB, and HTML

src/hypervisor.adoc, src/machine.adoc, src/supervisor.adoc
Also includes editorial updates from doc team.
=> Updated SDT and MDT clearing

Makefile
Some combination of asciidoctor and wavedrom is creating temporary files inside the source tree, which means multiple builds can't proceed at the same time without nondeterministic failures.  Fix by giving each build its own temporary copy of the source tree.
=> Fix parallel builds

src/machine.adoc, src/priv-preface.adoc, src/supervisor.adoc
=> Relax behavior of some HINTs when MXLEN > XLEN

src/images/wavedrom/rv64i_int-reg-reg.adoc
=> Fix funct7 codes in integer register-register inst wavedrom

src/supervisor.adoc
=> Move non-normative note to more logical position

src/b-st-ext.adoc
=> Fix mnemonics of Zbkx/Zbkb instructions

src/naming.adoc
Replace it in this example with Ztso.
Resolves #1523
=> Zam doesn't exist anymore

src/v-st-ext.adoc
=> fix inconsistent indentation of pseudocode (left justify all if it)

src/scalar-crypto.adoc
=> Delete outdated note about vector crypto

src/hypervisor.adoc
=> Delete hard-coded page number

src/vector-crypto.adoc
vragather -> vrgather in Zvkt section
=> Minor typo in vector-crypto.adoc

src/b-st-ext.adoc
=> Fix assembly representation of orc.b

src/c-st-ext.adoc
=> Expand acronyms of C.ADDI16SP/C.ADDI4SPN

marchid.md
Hi,
Asking a marchid for VexiiRiscv.
Here is a demo of the core : 
https://youtu.be/dR_jqS13D2c?t=117
Cheers
Charles
=> Add marchid for VexiiRiscv

Makefile
Reverts riscv/riscv-isa-manual#1630
=> Revert "Run docker as the current user"

src/priv-cfi.adoc, src/zpm.adoc
=> Zicfiss clarifications: CBO and PM

src/scalar-crypto.adoc
=> Remove claim that Zbkb is a subset of Zbb

src/mm-eplan.adoc
=> Fix misquote in RVWMO Rules

src/supervisor.adoc
=> G-stage PTE D-bit update relaxation

src/cmo.adoc
=> Mark CBIE field as WARL

src/priv-preface.adoc, src/riscv-privileged.adoc
Well, actually it isn't yet, but I'm preparing a PDF under the assumption that it will be.
=> priv 1.13 is ratified

src/hypervisor.adoc
Just a simple 1-line fix to the H chapter.
=> Fix for issue 1693 (HSLEN should be HSXLEN)

src/vector-crypto.adoc
https://github.com/riscv/riscv-isa-manual/issues/1718
=> fixing sail link

src/machine.adoc
This clarifies how the combination of misa.M and Zmmul affect the requirements on implementing multiply and division.
Fixes #1711
=> Clarify misa.M behaviour with Zmmul

src/priv-csrs.adoc
try resolve #1747
[Zkr - Entropy Source Extension](https://riscv-specs.timhutt.co.uk/spec/riscv-isa-release-e4d1542-2025-01-16/riscv-unprivileged.html#zkr)
=> Add seed CSR to CSR table

src/priv-csrs.adoc, src/zc.adoc
- [riscv-unprivileged.html#Zcmt](https://riscv-specs.timhutt.co.uk/spec/riscv-isa-release-f3f8a93-2024-11-28/riscv-unprivileged.html#Zcmt)
- [jvt CSR(0x0017)](https://riscv-specs.timhutt.co.uk/spec/riscv-isa-release-f3f8a93-2024-11-28/riscv-unprivileged.html#csrs-jvt)
=> Add jvt CSR to CSR table

src/vector-crypto.adoc
=> Correct typo

Makefile
=> Added Makefile target build-xml to build docbook XML format.

Makefile
Reverts riscv/riscv-isa-manual#1852
As per Tim's suggestion and James' agreement.
=> Revert "Added Makefile target build-xml to build docbook XML format."

src/bfloat16.adoc
Fixes [issue #1870](https://github.com/riscv/riscv-isa-manual/issues/1870)
=> Fixes #1870

src/zacas.adoc
In consultation with @ved-rivos.
=> Add non-normative AMOCAS memory ordering clarification

src/a-st-ext.adoc
=> Clarify that protection checks apply to failed SC

src/colophon.adoc, src/priv-preface.adoc, src/scalar-crypto.adoc
=> fix messsage typos and remove hyphen from reuse

src/b-st-ext.adoc
Proposed solution to issue #1979
=> Typographical fixes to xperm and packw instruction listing

src/v-st-ext.adoc
=> Clarify <nf> in asm syntax equals NFIELDS

src/machine.adoc, src/supervisor.adoc, src/zc.adoc
=> Add note about tvec/jvt register layout/alignment

marchid.md, src/cmo.adoc, src/hypervisor.adoc, src/indirect-csr.adoc, src/machine.adoc, src/priv-cfi.adoc, src/priv-preface.adoc, src/scalar-crypto.adoc, src/smcdeleg.adoc, src/smcntrpmf.adoc, src/smctr.adoc, src/smstateen.adoc, src/sstc.adoc, src/supervisor.adoc, src/unpriv-cfi.adoc, src/v-st-ext.adoc, src/vector-crypto.adoc, src/zawrs.adoc, src/zc.adoc
=> Hyphenate exception names

.pre-commit-config.yaml
using `pre-commit autoupdate` to update versions to latest
afterwards, I ran `pre-commit run --all-files` and it was clean.
=> chore: update pre-commit hook repo versions

src/scalar-crypto.adoc
Reverts riscv/riscv-isa-manual#2001
Text was ratified and should not be changed.
=> Revert "Remove a confusing sentences about hiding PC https://github.com/riscv…"

src/priv-csrs.adoc
=> Add srmcfg to CSR table

src/v-st-ext.adoc
https://github.com/riscv/riscv-isa-manual/issues/2029
=> strided fix

src/priv-csrs.adoc
Add supervisor/machine-level indirect register to CSR table
Resolves #2034
=> Add smcsrind/sscsrind to CSR table

src/priv-csrs.adoc, src/smcntrpmf.adoc
Add smcntrpmf extension CSR table.
=> Add smcntrpmf CSR table

src/machine.adoc
A line break was making so the text wan't bold
=> applied bold to a table title

.github/workflows/isa-build.yml
Due to an introduced bug in action-gh-release, workaround being applied to fix it, moving to action-gh-release@v2.2.2
=> Update version of action-gh-release

src/c-st-ext.adoc
=> Improve C extension HINT descriptions

src/c-st-ext.adoc
Follow-up to #2093
Supersedes #2098
=> Fix C.ADDI/C.NOP HINT description

src/m-st-ext.adoc
=> Fix the title of  m-st-ext.adoc

src/supervisor.adoc, src/zc.adoc, src/zilsd.adoc
=> add nonbreaking space between number and unit of measure

src/bfloat16.adoc, src/mm-formal.adoc, src/vector-crypto.adoc, src/zc.adoc, src/zpm.adoc
=> add missing Oxford commas

src/intro.adoc, src/rv-32-64g.adoc
The chapter was removed in 01e31a074bd12db11b230e0e9ac95e29b9b244cd.
=> Drop references to deleted chapter

src/cmo.adoc
=> Remove TODOs left for Sail operations in the CMO extension

antora.yml
This modifies the antora.yml file to contain the appropriate page attributes to give pdf download links to the antora UI.
=> created page attributes for antora to pull pdf links

src/images/wavedrom/c-cs-format-ls.edn, src/images/wavedrom/c-sp-load-store-css.edn, src/images/wavedrom/c-sp-load-store.edn, src/images/wavedrom/reg-based-ldnstr.edn, src/zpm.adoc
=> Remove a few dangling RV128 references

.pre-commit-config.yaml
=> Added --preserve-quotes to yamlfmt pre-commit check.

src/machine.adoc
=> Slightly improve PMP description
