riscv/riscv-isa-manual

src/extensions.tex
src/machine.tex
src/preamble.tex
src/supervisor.tex

PR as requested on isa-dev.  (I finally made a GitHub account for this.)
I had enough difficulty getting the list spacing to look reasonable and ended up with sufficiently different "spacing magic" in machine.tex and supervsior.tex that I added the "paralist" package to get its "compactitem" environment and avoid the whole mess.
I also had to think about where to actually define ILEN, and eventually decided that it makes the most sense in "Extending RISC-V" since it is influenced by support for extensions.

Add ILEN to simplify descriptions of {m,s}tval CSRs

---

src/rv32.tex

in RV32I comment.
Signed-off-by: ds2horner <ds2horner@gmail.com>

Change remaining SCALL/SBREAK reference to ECALL/EBREAK

---

src/machine.tex

It looks like there was a copy and paste bug between the RV32 and RV64 version of the `pmpaddr` diagram. This changes the diagram to correctly display the bit widths of the fields in RV64.

Fix typo in PMP address CSR bit field diagram

---

src/f.tex

This mnemonic has been adopted by the GNU assembler in addition to the
RNE/RTZ/RDN/RUP/RMM mnemonics currently described here.

Document the 'DYN' mnemonic for dynamic rounding mode

---

src/c.tex
src/intro.tex
src/machine.tex
src/supervisor.tex

This is still being debated; I'm making the PR so the PrivArch group can discuss something concrete.

Introduce IALIGN; propose misa.C semantics

---

src/supervisor.tex

Misaligned superpage exception occurs if **pte.ppn[i−1:0]!=0**. In the current specification instead of pte.ppn it given as pa.ppn.

Misaligned superpage exception occurs if pte.ppn[i−1:0]!=0

---

src/machine.tex

Following up on [issue 163](https://github.com/riscv/riscv-isa-manual/issues/163)...

Clarify URET with no user-mode traps support

---

src/rv32.tex

The current text does not actually specify whether `sub` puts `rs1 - rs2` or `rs2 - rs1` into `rd` (same for `add` but that one doesn't matter...).

Specify operand order for sub instruction

---

src/m.tex

Same as [#172](https://github.com/riscv/riscv-isa-manual/pull/172), bu for `div` (is it `rs1/rs2` or `rs2/rs1`?). `rem` seems to be defined in terms of `div` in the text, so that one is no longer ambiguous either. I wonder whether there are more noncommutative operations that would have also a similar ambiguity...

Specify operand order for div instructions

---

src/f.tex

Following up on [#179](https://github.com/riscv/riscv-isa-manual/pull/179). `FDIV` and `FSQRT` are actually defined in terms of the single precision instructions. `FSQRT.S` looked fine to me. I just rephrased the paragraph to be explicit about `FSUB.S` and `FDIV.S`.

FDIV.S and FSUB.S disambiguation

---

src/assembly.tex

Active voice, discussed in #177.
Also fix: the pseudoinstructions use absolute addressing, the base instructions are pc-relative. `symbol` is an absolute value and `auipc` is pc-relative.
If I understand correctly, `la rd, symbol` just puts `symbol` into `rd`. For 32 bit systems, it is essentially equivalent to `li rd, symbol`.

Switch to active voice

---

src/machine.tex

Explicitly mention that FS may be imprecise

---

src/a.tex

Commit 170f3c5 clarified that reservations can be cleared with an SC to
a dummy memory location. As discussed
<https://github.com/riscv/riscv-isa-manual/commit/170f3c52bd134ac90c3467f77925fdaa68e9b8f6#commitcomment-29386537>,
this patch makes it clear that the reservation "should" be cleared in
this way during a preemptive context switch.
Anyone writing preemptive context switch code should be forcibly
clearing load reservations. Although other mechanisms might be used,
this is the standard way of doing it (hence "should" rather than
"must").

Strengthen guidance on the need to clear a reservation using SC

---

src/memory.tex

Although purely a spelling issue, CCing @daniellustig as it touches memory.tex.

Correct an instance of lr{w|d}.aq.rl to lr{w|d}.aqrl

---

src/memory.tex
src/rv32.tex

Two small updates to the memory model text
1) Clarify that AMOs are always semantically considered stores
2) Attempt to clarify #186

Clarify that AMOs are always stores, and clarify fence.tso configs

---

src/hypervisor.tex

For the hypervisor extension, change the names of S-mode and U-mode when V = 1 to VS-mode and VU-mode, as agreed earlier.

Change hypervisor virtual mode names to VS-mode and VU-mode

---

src/machine.tex
src/supervisor.tex

Sections that are possibly distant in the document from the `mstatus` section are often affected by bits in the `mstatus` register.
I suggest helping the reader by mentioning that specific instructions/csrs are influenced by `mstatus` where those instructions/csrs are defined as opposed to exclusively in the `mstatus` section.
EDIT: Added a mention of TSR when describing SRET as well.
Additionally, when describing the `mstatus` TW field, shoud U-mode be mentioned in the case that user interrupts are enabled?

Help the reader by pointing at TVM, TW and TSR in the relevant sections

---

src/assembly.tex

The commit 3f05dd6ef3c7965f0d9c375c19bf4a4a76c331be from 2018-06-02 lost a closing brace.
This patch restores it.

Fix Typo: Recover a lost brace in assembly.tex

---

src/c.tex

The paragraph of text describing C.ADDI4SPN states the instruction is
RV32C/RV64C-only, but the opcode map indicates the instruction is
available for RV128C too.  This change updates the descriptive text,
assuming that the opcode map is correct.

Remove text stating C.ADDI4SPN is RV32C/RV64C-only

---

src/c.tex

In the RVC instruction formats figure and the respective subsection, the CA format row is changed such that the funct field is renamed to funct2, for consistency with the base ISA (which distinguishes between funct7 and funct3).
In the RVC instruction listings, the instructions with the CA format have the table formatting updated to match the new CA format, which was introduced in the commit 00557c314bd288c6eb511a201ce90bbdd4450d19.

Change funct to funct2 in the CA format

---

src/ztso.tex

As discussed (and approved) in the weekly memory model meeting, this change is the sister of a similar change in the RVWMO chapter. In each case the intent is to clarify that these memory models are completely defined in this specification. More specifically, the axiomatic definitions of the annotations are sufficient and should be used instead of any other understanding of these terms.

Clarification of ordering annotation semantics

---

src/rv32e.tex

Following on from #265, I think it would be worth documenting the decision to leave F and D extensions as introducing 32 FP registers when combined with RV32E. It's an obvious question/concern and the ISA manual tends to do a great job of anticipating these with commentary paragraphs - so let's add a new one.
I drafted something for the sake of moving the discussion forwards, but obviously you may wish to discard and put in your own words.

Add commentary on combining RV32E with extensions, mention Zfinx

---

src/supervisor.tex

I claim that this follows from the text in the following section, but it is clearly deserving of clarification.
https://groups.google.com/a/groups.riscv.org/forum/?utm_medium=email&utm_source=footer#!msg/isa-dev/EQQGObY1bQM/xm6imw-aCwAJ

Clarify that PTE updates aren't atomic w.r.t. the ultimate access

---

src/rv32.tex

I moved the stuff about ABI to commentary and greatly expanded it with details about what advanced hardware and the C extension assumes about usage of x registers.
Also arbitrary and capricious rewording of the description of x registers that might or might not make things more clear for people not already familiar with machine code and registers/instructions.

Clean up description of x registers. Add commentary about ABI

---

src/machine.tex

Perhaps its time to use \newcommand to avoid this fragility.

Fix a couple of typos and inconsistencies.

---

src/csr.tex
src/rv32.tex

Use non-hyphenated "side effects".
Use verb "cause" wrt "side effects".

Fix typos.

---

src/priv-csrs.tex

dscratch1 was missing from the listing, dscratch0 was named only dscratch.

Privileged Spec: Add dscratch0/1 to CSR listing

---

src/machine.tex
src/supervisor.tex

Submitted on behalf of Christoph Hellwig
For context, see https://groups.google.com/a/groups.riscv.org/d/msg/isa-dev/kL-2LhgUmcE/xxySlYT0CQAJ

Don't reference the SBI in normative privileged spec sections

---

src/c.tex

This PR essentially copies the information from the encoding table at the
end of the chapter into the mainline text.  The intent is to remove any
doubt about what happens when an instruction's operand constraints are
not met.

Clarify reserved/HINT encodings in C chapter text

---

src/rv64.tex

Adds the missing FENCE instructions to the table of RV64 HINT instructions.

Adding FENCE to the table of RV64 HINT instructions

---

src/machine.tex

The commentary says this is allowed, but the normative text doesn't.  I don't like this behavior, but the manual should at least be self-consistent.

Allow mcycle to be shared between harts

---

src/machine.tex

Other WARL registers seem to be explicit (e.g. "The misa CSR is a WARL
read-write register..."). This patch adds a similar indication for
mtvec. This consistency is important, as otherwise the reader will spend
time trying to determine if the behaviour is different. You can
determine it's WARL by reading the field layout diagram, but I think a
little redundancy in favour of easing readability makes sense.
At least one simulator started off trapping on invalid field
modifications
<https://lists.gnu.org/archive/html/qemu-devel/2018-04/msg04510.html>.

Clarify that mtvec is WARL

---

src/machine.tex

Up to now the behavior of `cycleh`, `instreth`, `hpmcounterN` and `timeh` wasn’t defined in the privileged spec, other than in the initial table.

Define Upper-Half User-Level Timer CSRs for RV32I

---

src/priv-csrs.tex

A fix for issue #440.
Includes fixes for trailing whitespace.

Allow RV32E to access the same CSRs as RV32I

---

src/machine.tex

Behaviour when endian fields are hard-coupled is not well defined.
If both fields are written with opposite endianness which takes precedence,
or are the fields left unchanged?
Both approaches are currently used in CSRs.
Further complicating the situation on RV32 systems is the separation
of UBE from MBE/SBE into two CSRs.
Whereas precedence and conflict cannot be determined for two discrete CSR
updates I propose instead that controlled fields not be directly writable.
Signed-off-by: David Horner <ds2horner@gmail.com>
[ I would have preferred to introduce the concept of "controlling fields" which would be generally applicable to the other situations where this coupling occurs and allows for soft coupling in addition to  "hard-wiring". More possibilities, including transition setting by …

ignore write to "controlled" SBE and UBE.

---

src/rvwmo.tex

The preface says the RVWMO is version 2.0 and has been ratified, but the text
of the standard still says it's version 0.1.
Signed-off-by: Palmer Dabbelt <palmerdabbelt@google.com>

The RVWMO is version 2.0

---

src/intro.tex

It was pointed out that "custom extension" is not explicitly defined.  Define it, and make it clear that the three defined categories are mutually exclusive.
Also, clarify what "conflict" refers to (it's not the encoding itself that conflicts with an extension; rather, it's the base ISA and its various extensions that might conflict in their uses of an encoding).

Clarify and define categories of extensions

---

src/rv32.tex
src/rv64.tex

The text vacillates between describing the U-immediate as a 20-bit
quantity, and as a 32-bit quantity whose lower 12 bits are zero.
Standardize on the latter.  Note the discrepancy in the ASM syntax.
Resolves #452

Consistently claim that U-immediate is 32 bits, not 20 bits

---

src/extensions.tex

The text currently mandates extensions to build on top of any base
integer ISA, but only lists two of them (RV32I and RV64I). Add the two
remaining ones (RV32E and RV128I) as well.

Extensions: List all integer base ISAs

---

src/rv64.tex

Claire Wolf pointed out in email to [isa-dev] that "The 2048 points missing on the higher [end] are "tacked on" on the lower end". This PR adds this detail to the previous commentary.

Clarify offset range in RV64I

---

src/zifencei.tex

This sequence only synchronises the remote harts; the local hart still needs to perform a normal FENCE.I.

Clarify that FENCE + remote FENCE.I is insufficient for local hart

---

src/supervisor.tex

Based on discussion on the mailing list, the instruction fences accesses not just to one leaf PTE but to any leaf PTE that includes the address (subject to address space constraints specified via rs2).

Clarify semantics of sfence.vma with rs1 != x0

---

src/hypervisor.tex

For the hypervisor extension, add another exception type, "virtual instruction exception", that substitutes for the illegal instruction exception in cases where a hypervisor is expected to emulate the instruction.  This saves time because this exception type can be delegated directly to HS mode, whereas illegal instructions will typically be processed first in M mode and delegated to HS mode only by software.

Add virtual instruction exceptions to the hypervisor extension

---

src/hypervisor.tex

Add (restore) field VTW to CSR hstatus, analogous to mstatus.TW.  Also, better clarify the rules for the exceptions raised by instruction WFI when in virtual operating modes (VS mode and VU mode).

Add VTW field to hstatus; improve rules for WFI in virtual modes

---

src/supervisor.tex

Seems like a simple copy-paste error introduced in f251913

Fix Sv48 VALEN typo

---

src/csr.tex

More clearly distinguished the ordering rules that apply to the same hart from those that involve other agents (harts and devices).  Made CSR side effects completely synchronous to the same hart by default.  (Deviances are still allowed, when documented.)  Added a comment that rules about the reordering of CSR accesses in the global memory order should probably be moved to the RVWMO chapter.

Clarifications to the perceived ordering of CSR accesses and their effects

---

src/c.tex
src/extensions.tex
src/hypervisor.tex
src/machine.tex
src/priv-csrs.tex
src/rv32.tex
src/rv32e.tex
src/rv64.tex
src/supervisor.tex

In Volume I, section 1.3, "RISC-V ISA Overview", the words *reserved* and *custom* are defined as disjoint categories.  I believe the phrase "reserved for custom use" undermines the meaning we usually want to convey with the word *reserved*.

Change "reserved for custom" to "designated for custom"

---

src/hypervisor.tex
src/machine.tex
src/supervisor.tex

Instead of describing CSR fields for XLEN (SXL, VSXL, UXL) and endianness (SBE, VSBE, UBE) as possibly being "hardwired" to another field, describe them as possibly being read-only fields with matching values.

Change "hardwired to other field" to "read-only field"

---

src/priv-csrs.tex

These registers may be written with process ID information by operating systems running in their respective privilege levels.  A debugger may use tdata3 (aka textra) to  qualify breakpoints based on a comparison of context register(s) with corresponding trigger field(s).  These registers and comparison fields are described in the RISC-V Debug Specification.

Add scontext, hcontext, and mcontext CSRs for Debug

---

src/dep-table.tex

FCVT.D.S will never round,  frm* and if rm=111 shouldn't be included

change FCVT.D.S frm to useless

---

src/hypervisor.tex

The consequences of disabling an extension by clearing a bit in misa is specified with the misa CSR.

Disabling H extension does not ensure illegal instruction traps

---

marchid.md

According to [marchid.md](https://github.com/riscv/riscv-isa-manual/blob/master/marchid.md)
> Open-source project maintainers may make pull requests against this repository to request the allocation of an architecture ID.
I would like to request an architecture ID assignment (architecture ID 19) for the [NEORV32 processor](https://github.com/stnolting/neorv32).
:)

add architecture ID for NEORV32 core

---

src/machine.tex
src/supervisor.tex

This is a normative change, but it is backwards compatible, since writing 0 to mtval remains a legal option.
Resolves #600

Both HWBPs and EBREAKs populate mtval

---

src/machine.tex

Even after having read through various discussions, I keep getting confused when reading the privileged document's table of content and seeing `mtime` and `mtimecmp` listed under `3.1 Machine-Level CSRs`: I go and look for their location in the CSR address space and can't find them, and then realise that "ah yes, these are memory-mapped! I should have remembered that".
If I understand correctly, `mtime` and `mtimecmp` are *not* CSRs in that they are not accessible via the various CSR instructions, and only the separate `time`(and `timeh`) CSR provides a window to `mtime` via the CSR space.
This PR suggests conveying this straight from the table of content.
Additionally, I wonder about what a 
> memory-mapped machine-mode read-write register
means when it comes to exceptions. I presume the …

Dedicated section for machine-level memory-mapped registers (specifically mtime/mtimecmp)

---

src/machine.tex

Make unused misa fields 0 (WARL) rather than WLRL.

---

src/machine.tex

Clarify that mtime >= mtimecmp results in a *machine* timer interrupt being posted.

Clarify type of timer interrupt

---

src/preface.tex
src/riscv-spec.tex
src/rv32.tex
src/rv64.tex
src/zihintpause.tex

Add PAUSE hint

---

src/a.tex

Currently due to the sequential description in use it technically says that you should use the just-loaded value in that case, when that is of course not what's intended, nor what implementations do.

Clarify that AMOs use the original address when rd == rs1

---

src/machine.tex
src/supervisor.tex

Note that this change does not consider the forthcoming sPMP proposal.  We'll have to update the text to say that SUM should be hardwired to 0 if satp.MODE is hardwired to 0 and sPMP is not provided.
I proposed similar wording in the sPMP proposal: https://docs.google.com/document/d/1x7esOSBFfpcbDHaRPpe5NEWmav1_8der_nB25Hd5hqs/edit#

SUM should be hardwired to 0 for cores without paging

---

.travis.yml

Updates the Travis CI build environment from Ubuntu 14.04 (Trusty Tahr), which is end-of-life, to to Ubuntu 20.04 (Focal Fossa).
Please also note that [travis-ci.org](https://travis-ci.org/) will be shutting down. See [Migrating repositories to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

Travis CI: Update build environment to Ubuntu 20.04 Focal

---

src/m.tex

Contributed by @allenjbaum, with some of my own edits.

Add Zmmul section to M chapter

---

src/zihintntl.tex

Locally define "target instruction" term as a shorthand for the
subsequent instruction to which the HINT applies.

Change to use more common terms.

---

src/memory.tex

Explicitly state the PMAs required for this set of mappings to allow C
to run on RISC-V.

State PMAs that are required for these mappings.

---

src/machine.tex

This is technically a semantic change: we are strengthening the R=0 W=1 combination from being "reserved" to being invalid in the WARL sense.

PMP RWX are collectively WARL, with R=0 W=1 being illegal

---

marchid.md

This PR requests the 25 marchid for XiangShan. It’s an open-source high-performance RISC-V processor maintained by Institute of Computing Technology, Chinese Academy of Sciences (ICT, CAS).

Add marchid for XiangShan

---

src/machine.tex

It would be nice to use a fixed width font for fields too.
Are the reference names in the document or inside https://github.com/riscv/riscv-config/blob/master/riscv_config/schemas/schema_isa.yaml ?
There are probably a few fields starting with a capital letter in the documentation while they are lowercase in yaml.

CSR should have been used instead of field

---

src/priv-csrs.tex

In particular, relabel "user CSRs" to be "unprivileged and user CSRs".

Improve labels of CSR categories

---

src/machine.tex
src/priv-preface.tex

But of course it can be hardwired to 0 in most implementations.
cc @jhauser-us

mstatush is not optional in priv-1.12 for RV32

---

src/machine.tex

The definition gives the implementation the flexibility of hardwiring mtval to 0, but also says that mtval is always written on certain exceptions.  This is, at a minimum, confusing since if mtval is hardwired to 0, those writes are fruitless.
Resolve by conditioning the sentence on whether mtval is hardwired to 0.
@jhauser-us -- this is not the resolution we discussed last night, but I think it does the trick, right?

Resolve contradiction in mtval definition

---

build/Makefile

something many code editors constantly try to fix and thus create unwanted changes.

trivial: Remove trailing spaces in Makefile

---

src/hypervisor.tex

For the hypervisor extension, define "privilege mode" as the combination of virtualization mode and the new concept of "nominal privilege mode".

Rename hypervisor extension "operating mode" to "privilege mode"

---

src/hypervisor.tex
src/machine.tex
src/supervisor.tex

Supersedes #590
This version is much more relaxed but nevertheless covers the important bases of SRET and explicit toggling of xip/xie.

Improve description of interrupt traps

---

src/hypervisor.tex

One, clarify the rules for virtual instruction exceptions by adding the concept of *HS-qualified*; and two, make a special case for accesses to 32-bit high-half CSRs like `cycleh` and `htimedeltah`.  Also, when WFI is attempted in VU mode, the exception depends on `mstatus`.TW.

Improve rules for virtual instruction exceptions, again

---

src/machine.tex
src/supervisor.tex

This approach is more extensible, and now implicitly includes writes to sstatus.SIE / mstatus.MIE, as it should.

Generalize interrupt trap condition evaluation conditions

---

src/hypervisor.tex

1. For RV32, mstatush is now always required to exist.
2. mstatus.MPP is not just one bit.

Corrections to mstatus in hypervisor chapter

---

marchid.md

This PR requests the 26 marchid for Hummingbirdv2 E203. 
It’s an open-source RISC-V processor Core and SoC, which developped and maintained by Nuclei System Technology.

Add marchid for Hummingbirdv2 E203

---

src/csr.tex

The non-normative text erroneously suggested that only accesses to time/cycle/mcycle need be ordered by FENCEs.  In fact, other CSR accesses are also visible to other harts, including interrupt-pending CSRs.
(The preceding normative text has no such deficiency.)

Fix non-normative text about CSR ordering

---

src/f.tex
src/intro.tex
src/rv32.tex
src/zifencei.tex

The term *execution environment interface* (EEI) appears to be intended to refer to the most applicable "binary interface" standard for the execution environment, such as the Linux RISC-V ABI or the RISC-V SBI.  However, such standards never fully specify every detail that is relevant to determining RISC-V instruction execution.  In particular, while a specific version of the Linux RISC-V ABI may require that certain features are implemented and others are not implemented, there are always some optional features or behaviors, or ISA extensions, about which the ABI is ambivalent.  As a consequence, in almost every instance where the base ISA manual says that something is specified by the EEI, it should really say, "specified by the EEI, or, if not, then determined by the underlying …

Replace "EEI" with "execution environment"

---

src/hypervisor.tex
src/priv-csrs.tex
src/supervisor.tex

When different privilege modes have different values for XLEN, the terms _RV32_ and _RV64_ are not sufficient to indicate the width of a privileged CSR that is accessed from a more-privileged mode (e.g. when 32-bit `vsatp` is accessed from 64-bit HS mode).  Where needed, replace "RV32" and "RV64" with more specific references to the correct XLEN.

Clarify widths of privileged CSRs

---

src/hypervisor.tex

Raise a virtual instruction exception when V = 1 if an attempted instruction is HS-qualified but is explicitly blocked by either a hypervisor CSR or a supervisor CSR.  Previously, the document was inconsistent whether an illegal instruction or virtual instruction exception is raised when an instruction is blocked from executing in VU mode solely by a supervisor CSR such as `scounteren`.

Make virtual instruction exceptions more consistent for VU mode

---

src/intro.tex
src/machine.tex
src/priv-preface.tex

These constraints are better expressed as PMAs, and so we relax the unprivileged spec to always allow speculative implicit reads "unless otherwise specified", then move the constraints into the PMAs.
This proposal piggybacks on the non-idempotence PMA, constraining implicit reads to within a power-of-2 region of a non-speculative implicit read. Furthermore, speculative instruction fetch can also access the subsequent power-of-2 region.
No need to explicitly mention idempotent regions, because this construction implicitly allows speculative accesses to them.

Speculative implicit reads, v2

---

src/colophon.adoc
src/riscv-isa-unpriv.adoc

- fixed missing newline
colophon.adoc
- fixed first table - missing entries
- bolded section header and term "Ratified"

riscv-isa-unpriv.adoc

---

src/intro.adoc
src/rv32.adoc
src/zicsr.adoc

Just so I don't lose track of it, here are the issues I noticed that I _didn't_ attempt to address:
Sec. 1.5.1:
- References to the instruction-length encoding figure show up in the text as "[instlengthcode]" instead of "Figure 1.whatever".  I guess the reason is that the figure isn't captioned?
- Likewise references to "Chapter [extensions]"
Sec. 1.6:
- "Characteristics of traps" table caption is being rendered incorrectly; it's showing up in garbled form in the main text.
Sec. 2.1:
- Figure 1 is low quality (looks like a screenshot from TeX spec) and needs to be redone.
Sec. 2.9:
- The HINT table was pretty messed up; I tried to fix it, but it needs further review.
Sec. 6.2.1:
- Encodings for SRAI and SRAIW are incorrect.  Their imm[11:6] field should be 010000, not 100000.
Chapter 16: …

Improvements to Intro and RV32I chapters

---

src/hypervisor.tex
src/machine.tex
src/priv-preface.tex
src/riscv-privileged.tex
src/supervisor.tex

* Clarify that when the address-translation algorithm reaches a PTE
in which reserved bits are set, a page-fault exception must be raised
* Clarifications regarding speculative address translation and
address-translation caches
* Clarify wording regarding bits being reserved for future standard use
* Allow speculative PTE A bit updates
* Slightly relax the PTE A/D bit update atomicity requirements
This PR supersedes #611.  It is the same content, but refactored to better align with the logistics of the RISC-V ratification process.

Various minor virtual memory clarifications

---

src/supervisor.tex

This is a strengthening of Svpbmt, in response to public-review feedback.

Accesses to pages with mismatched attrs are I/O _and_ memory wrt FENCE

---

src/hypervisor.tex

Account for the fact that, once again, memory access traps may write zero to `stval`.

Memory access traps may write zero to stval

---

marchid.md

This is a 3-stage `RV32I` core, with optional support for `M`/`C`/`Zba`/`Zbb`/`Zbc`/`Zbs` and debug support. It passes the ISA compliance tests, riscv-formal, OpenOCD DM compliance tests and the end-to-end debug tests from riscv-tests/debug.
[Github](https://github.com/Wren6991/Hazard3)
[PDF documentation](https://github.com/Wren6991/Hazard3/blob/master/doc/hazard3.pdf)
The license is DWTFPLv3, which is effectively a public domain dedication.

Add Hazard3 to open-source marchid list

---

src/priv-csrs.tex

Seems like the kind of thing that could've gone without saying, but it has
come up in conversation a number of times---including wrt. the recent
CSR Field Modulation discussion in #782.
So, make it crystal clear.

Clarify that implicit reads of CSRs return same value as explicit reads

---

src/machine.tex

Interrupts and exceptions are different things (per unpriv spec section 1.6).

Proper terminology

---

src/hypervisor.tex

The hypervisor extension (H) was shown as version 1.0.0, but there is no need now for a third component to the version number.

Change H extension to version 1.0

---

src/supervisor.tex

Restructure the listing of exceptions raised for SINVAL.VMA, HINVAL.VVMA, and HINVAL.GVMA, as follows:
- List exceptions that occur absent the hypervisor extension first.
- Replace obscure "when V=1" with "in VS-mode or VU-mode".
- Add that attempts to execute SINVAL.VMA in VU-mode raise a virtual instruction exception.

Rework the description of exceptions for Svinval

---

src/hypervisor.tex

HFENCE.VVMA orders only those implicit reads done for VS-stage address translation, and HFENCE.GVMA orders only those implicit reads done for G-stage address translation.  Implicit reads that might access the same data for other reasons (due to sharing of page tables, for example) are not impacted.
Removed a couple instances of the word *subsequent* that were easily misinterpreted.

Better clarify the effects of HFENCE.VVMA and HFENCE.GVMA

---

.github/workflows/build-pdf.yml

In order to test the new build of the Asciidoc using a GitHub action off
the "convert2adoc" branch, the master branch must have a GitHub action
with the same name.
Signed-off-by: Stephano Cetola <scetola@linuxfoundation.org>

add dummy GitHub action

---

.github/workflows/build-pdf.yml

Currently there is a branch which contains the unprivileged
specification code in asciidoc format. This action should only be run on
that branch. Once the conversion of the privileged specification is
complete as well, this action can be updated to build the complete set
of specs.
Signed-off-by: Stephano Cetola <scetola@linuxfoundation.org>

Update GitHub action to build Asciidoc branch

---

src/hypervisor.tex

Remove the duplicated "the".
Signed-off-by: Dong Du <Dd_nirvana@sjtu.edu.cn>

hypervisor: fix typos

---

src/memory.tex

Updates the second possible scenario in which a0=1 to state that (c)
appears before (b) would result in a0=1 but is forbidden due to
violation of the Load Value Axiom. The current description states that
a0=1 if (a) appears before (b) in global memory order, which would not
be the case as (b) stores the immediate 2 to the same address 0(s0)
after (a) stores the immediate 1.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
cc @daniellustig @aswaterman 
This is based on my own understanding of the Load Value Axiom and the litmus test in question. Please feel free to close if my interpretation is incorrect.

Fix ordering in A.1 litmus test forbidden execution explanation

---

src/hypervisor.tex

The Sv57 example wasn't included in the list of expanded widths for the
*x4 modes.
Signed-off-by: Dylan Reid <dgreid@rivosinc.com>

hypervisor: Add Sv57 to &x4 address witdth list

---

src/zihintntl.tex

It seems too minor but this extension defines four hint variants, not three.
1. `NTL.P1` / `C.NTL.P1`
2. `NTL.PALL` / `C.NTL.PALL`
3. `NTL.S1` / `C.NTL.S1`
4. `NTL.ALL` / `C.NTL.ALL`
Possible old list of "three" hint instructions follow:
1. `NTL.L1`
2. `NTL.L2`
3. `NTL.LLC`

Zihintntl: Fix number of hint instruction variants

---

src/c.tex
src/rv32.tex
src/rv64.tex

Assuming Zihintntl extension to be frozen, ratified and merged, this pull request changes refines various locations related to HINT instructions.  Note that there are some changes *not* involving Zihintntl extension.
Commit ea9410a6a5ea by @aswaterman added "PAUSE" instruction and changed semicolon to colon.
Commit 1 and 2 ports this change to RV64I and RVC (RV64I change is a must).
From section 18.7 "HINT Instructions" (RVC):
> RVC HINTs do not necessarily expand to their RVI HINT counterparts. For example, `C.ADD x0, t0` might not encode the same HINT as `ADD x0, x0, t0`.
However, Zihintntl extension actually defines `C.NTL.ALL = C.ADD x0, t0[x5]`, which encodes the same hint as `NTL.ALL = ADD x0, x0, t0[x5]`.  This commit changes `t0[x5]` to `a0[x10]` to use unused encoding space …

Refine HINT Instruction references (including tables)

---

src/instr-table.tex
src/priv-instr-table.tex

Now, the entire instruction tables are generated by [riscv-opcodes](https://github.com/riscv/riscv-opcodes).
Related: riscv/riscv-opcodes#99
But CMO instructions are manually deleted because they are not in the ISA Manual yet.
Relatively large diff came from removing trailing spaces (riscv/riscv-opcodes#98). Others are came from slight instruction order modifications (on Zfh, hypervisor and Svinval instructions).

Update Instruction Tables based on riscv-opcodes

---

marchid.md

Adds [CV32E41P](https://github.com/openhwgroup/cv32e41p) to the MARCHID list.  The core started its life as a fork of the CV32E40P core to implement the official RISC-V [Zfinx](https://github.com/riscv/riscv-zfinx/blob/main/zfinx-spec-20210511-0.41.pdf) and [Zc*](https://github.com/riscv/riscv-code-size-reduction/releases/tag/V0.50.1-TOOLCHAIN-DEV) ISA extensions.
Closes https://github.com/openhwgroup/cv32e41p/issues/7

Adds CV32E41P to MARCHID

---

src/zihintntl.tex

LaTeX produces this during build process:
```
LaTeX Warning: Label `chap:zihintpause' multiply defined
```
It looks like the `chap:zihintpause' label was copy-pasted
from Zihintpause chapter.
The commit sets appropriate label for the Zihintntl chapter.

Zihintntl: fix chapter label

---

src/hypervisor.tex

A HFENCE.GVMA is still required after changing PMPs affecting VS-stage translation when vsatp.mode=ON and hgatp.mode=BARE.

Hypervisor: use HFENCE.GVMA after PMP write to synchronize VS-enabled-G-disabled

---

src/naming.tex

This branch resolves two issues on Table 28.1 (Standard ISA extension names):
1. `B`, `K` and `J` are not going to be single-letter extensions, making those appearance in the Table 28.1 unnecessary (or even misleading and harmful).  
Those letters are referred in the section 28.6 (Additional Standard Extension Names) and Table 28.1 does not need them.
2. `V` is plural (actually `V` is [*an extension*](https://github.com/riscv/riscv-v-spec/releases/tag/v1.0) with some variable parameters such as vector length).
See commit c1c77c4902d5e7c58613d725d09d66a2a743da1c for background of this proposal for `B` and `J`.
For `K`, those might be helpful:
1. https://github.com/riscv/riscv-crypto/releases/tag/v0.9.3-scalar (with `misa.K`)
2. https://github.com/riscv/riscv-crypto/releases/tag/v0.9.4-scala …

Strict single-letter extensions on Table 28.1 (Standard ISA extension names)

---

src/naming.tex

... as commented by Andrew Waterman:
https://github.com/riscv/riscv-isa-manual/pull/838#issuecomment-1107473631
Related: #838

D extension is implied by V extension

---

src/machine.tex

And explain why "implemented and disabled" is considered a contradiction, while "implemented and enabled" is redundant.

Clarify what is meant by "implemented"

---

src/opcode-map.tex

`V` extension corresponding new base opcode OP-V (`0b1010111`) is now ratified and this table is updated.
Although vector instructions are not listed in Chapter 26, noting that this base opcode is used seems good to me. If `Zp*` extensions are ratified, OP-P (`0b1110111`) can be listed here, too.

Add OP-V to base opcode map

---

src/rv32.tex

The previous text explicitly required four-byte alignment, which is not the case in the presence of extensions that reduce IALIGN.

Make base ISA text generic with respect to IALIGN

---

src/counters.tex

It's effectively an unprivileged constraint, not just user-level.

Clarify that time CSR one-tick constraint is not merely user-level

---

src/supervisor.tex

@gfavor pointed out that this is already stated elsewhere:
> fundamentally, the tablewalk pseudo code says "if any bits or encodings that are reserved for future standard use are set within pte, stop and raise a page-fault exception corresponding to the original access type."
https://github.com/riscv/riscv-isa-manual/blob/f518c259c008f926eba4aba67804f62531b6e94b/src/supervisor.tex#L1677-L1679
Nevertheless, I think this clarification would be equally as helpful here as the existing adjacent statement for non-leaf PTEs.

Svpbmt: leaf PTE reserved value=3 page fault

---

src/naming.tex

Updating 'G' definition to match the definitions in section 28.3 and the beginning of chapter 26 to avoid confusion for casual readers (although technically all three are equivalent based on D implying F implying Zicsr).

Updating 'G' definition

---

src/naming.tex

Signed-off-by: John Zaitseff <J.Zaitseff@zap.org.au>
Fixes bug #875

Fix missing backslash

---

src/c.tex
src/machine.tex
src/preface.tex
src/priv-csrs.tex
src/priv-preface.tex
src/rv32.tex

We were using a mix of the two, with a bias towards the former.
Resolves #887

Standardize on {\tt pc}, rather than PC

---

marchid.md

This is a 7-stage 2-way superscalar RV64I core, with optional support for M extension/ MMU and S/U mode support. It has been submitted to tapeout at efabless MPW-7 shuttle.

Add RISu064 to open-source marchid list

---

marchid.md

We would like to add the AIRISC processor to the `marchid` list and thus request an official architecture ID for the core.
The AIRISC is an ASIC- and FPGA-proven processor system targeting embedded AI and developed by the Fraunhofer Society.
- GitHub Repository: [github.com/Fraunhofer-IMS/airisc_core_complex](https://github.com/Fraunhofer-IMS/airisc_core_complex)
- Offical webpage: [www.airisc.de](https://www.airisc.de/)

Add marchid for Fraunhofer-IMS AIRISC

---

.github/workflows/build-pdf.yml
.github/workflows/create-release.yml

This PR does 3 things:
1. Upgrades the build-pdf.yml workflow to be Node 16 and remove the deprecated messages.
2. Make build-pdf.yml workflow callable from other flows
3. Adds a create-release.yml workflow for building releases and including the PDF asset (thus the need to make build-pdf callable).
Note: The new create-release.yml workflow still has some warnings (3) about deprecated Node 12 APIs.  More work is needed to figure out how to handle the non-maintained create-release and upload-release-assets workflows.  However, for now, the new flow is beneficial.

Riscv isa asciidoc

---

src/a-st-ext.adoc
src/colophon.adoc
src/images/wavedrom/csr-instr.adoc
src/images/wavedrom/ct-unconditional-2.adoc
src/images/wavedrom/ct-unconditional.adoc
src/images/wavedrom/immediate.adoc
src/images/wavedrom/immediate_variants.adoc
src/images/wavedrom/int-comp-lui-aiupc.adoc
src/images/wavedrom/int-comp-slli-srli-srai.adoc
src/images/wavedrom/int_reg-reg.adoc
src/images/wavedrom/integer_computational.adoc
src/images/wavedrom/nop.adoc
src/intro.adoc
src/resources/themes/riscv-spec.yml
src/rv32.adoc

Andrew's suggestions:
Fixed mid-table rows that should be highlighted like headers. Fixed broken double quotes.
Fixed single quotes converted to backticks in errors. Removed cite ref to OpenRISC spec, which is wrong. TO BE FIXED.

Fixed mid table header highlighting and quotes.

---

src/machine.tex

Current spec says the following about xRET clearing mstatus.MPRV:
```
... and xPP is set to the least-privileged supported mode (U if
U-mode is implemented, else M). If xPP̸=M, xRET also sets MPRV=0.
```
It may confuse people to think that the condition to set MPRV=0 is
to compare the updated xPP value against M, as this sentence comes
right after the xPP update sentence.
Change 'xPP' to its original value 'y' which avoids the confusion.

Clarify xRET clearing mstatus.MPRV when leaving M-mode

---

marchid.md

We would like to request an architecture ID for Proteus.
Proteus is a RISC-V core (currently supporting the RV32IM instruction set) developed at KU Leuven. It was developed with extensibility in mind, to facilitate easy prototyping and evaluation of extensions to hardware and the ISA.

Add Proteus to list of march IDs

---

src/rnmi.tex

Clarify that NMIE only affects M-mode synchronous exception behavior.
Also state that MNRET clears MPRV when returning to less-privileged modes.

Smrnmi fixes

---

build/Makefile

This changes adds the following:
* Use the := assignment operator for immediate assignment, to avoid unnecessary recomputations.
* Extract common asciidoctor-pdf options into a single variable (ASCIIDOCTOR_OPTS) to avoid redundancy.
* Define a SRCDIR variable for the source directory path to simplify changes.
* Use pattern rules to generate PDFs and make the target depend on the source file, so the build is only triggered when the source file has been modified.
* Add a clean target to remove generated PDFs.

Add specific targets for priv and unpriv build

---

src/zfinx.tex

As I noted previously in <https://github.com/riscv/riscv-zfinx/issues/14>, it's incorrect to say that floating point values passed in GPRs are sign-extended in the standard calling convention. The [current, ratified psABI](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/6cda8927232dc59424426f4dd0de2e0723d865fb/riscv-cc.adoc) states "Floating-point reals are passed the same way as aggregates of the same size" and the relevant part from the description of aggregates is "Bits unused due to padding, and bits past the end of an aggregate whose size in bits is not divisible by XLEN, are undefined."

Fix incorrect description of the calling convention for floats passed in GPRs

---

.github/workflows/build-pdf-and-html.yml
build/Makefile

This commit introduces a new step in the GitHub Actions build process, improves the Makefile's cleanup function to remove lingering files, and expands the JUNK variable to include additional file extensions for a more thorough cleanup.

Update the path for Makefile cleanup and GitHub Actions build

---

.github/workflows/build-pdf.yml

This change fixes the build issue, add a release step and update the backend to run the build within a container. It also includes the following:
- Add `create_release` input to `workflow_dispatch` event
- Create and push a git tag when manually triggered with `create_release=true`
- Create a non-draft release with the generated PDF when manually triggered with `create_release=true`

Fix the build issue

---

src/naming.adoc

Related commit
* (b61dd437) Strict single-letter extensions on Table 28.1 (Standard ISA extension
* (6b1754c8) D extension is implied by V extension
* (f5f9c270) Delete more nonexistent extensions from the naming constraints
* (7249db97) Remove multi-letter H* extensions from naming
* (db7a4a0d) Add single-letter "H" extension to the table
* (d8786eed) Updating 'G' definition
Related to #1035

Backport changes to naming.adoc

---

src/images/bytefield/rvc-instr-quad2.adoc

This PR fixes #1037 
1. Fix the definition of `C.LWSP`.
2. Added definition of `C.LQSP`.

Fix error in RVC Instruction Set Listings: Quadrant 2

---

src/a-st-ext.adoc
src/mm-eplan.adoc

This is a fairly minimal fix to the unprivileged spec to prepare us for atomics ABI work. It fixes some oversimplifications that were uncovered during the load-acquire store-release mailing list discussions. Some of the observations behind the changes came from Palmer Dabbelt. Andrea Parri, and others. It also fixes some inconsistencies with A.6, and adds a clarification there.
Note that the use of LR/SC to implement "sequentially consistent" atomics primitives is subtle, and depends on the precise semantics, and how other atomics are implemented. I tried to tread the fine line between inaccuracy and turning this into a memory model tutorial.
This is the adoc version of pull request #992 .

Fixes for Atomics wording (adoc)

---

src/a-st-ext.adoc

Use _doubleword_ instead of "64-bit word" and _word_ instead of "32-bit word"

A-ext chapter: 64-bit word => doubleword; 32-bit word => word

---

src/c-st-ext.adoc

In https://github.com/riscv/riscv-isa-manual/pull/1001,
I think "Reserved for future standard use" in C extension's table should have been replaced with "Designated for future standard use".

Change "Reserved" to "Designated" in RVC HINT instructions table

---

src/hypervisor.adoc

`mtval2`'s doesn't render, suggesting a space to fix that but it might not be the best answer

fix formatting

---

src/images/wavedrom/ct-conditional.adoc

Bit 12 was merged with bits 10:5, but it was still labeled as 6 bits instead of 7. Bits 4:1 and 11 were merged in the label but not in the diagram and they were merged backward in the label. Merge them in the diagram and fix the label.

Make "Conditional Branches" wavdrom consistent

---

src/images/wavedrom/load-reserve-st-conditional.adoc

The name of this bit is rl and not r1.

Correct Name of LR/SC Instructions rl bit

---

src/images/wavedrom/c-int-reg-immed.adoc

Properly align the ADDI16SP immediate in wavedrom. Remove the bit brackets from the immediates because the instructions do not uniformly follow the same immediate format.

Make "Integer Register-Immediate Operations" Consistent

---

src/images/wavedrom/c-cs-format-ls.adoc

wavedrom diagram used "types" instead of "type" so the proper formatting was not applied.

Resolve incorrect formatting in CS format

---

src/machine.adoc
src/priv-preface.adoc

@gfavor FYI
@jhauser-us please check my wording.  It's a little obtuse because I was trying to constrain the set of legal values for SXL's WARL purposes.

priv-1.13: clarify that MXLEN >= SXLEN; constrain SXLEN >= UXLEN

---

src/images/bytefield/rvc-instr-quad1.adoc

It removes "(RV64/128)" from the `C.XOR` instruction in the RVC Instruction Set Listings.

`C.XOR` is not RV64/RV128 only

---

src/images/bytefield/rvc-instr-quad1.adoc

The lower immediate for C.ADDI16SP is [4|6|8:7|5] instead of [4:0]

Fix C.ADDI16SP immediate

---

src/colophon.adoc
src/counters.adoc

Resolves the same issue as #1008.
*   It is based on the latest AsciiDoc-based documentation.
*   Version numbers are set to correct 2.0.
*   I didn't split "Counters" to `Zicntr` and `Zihpm` separate rows (of course, I can change that easily and tell me if I need to).

Counters are now ratified (with version 2.0)

---

build/.gitignore

The author forgot to add this to the initial PR (#1089) because `*.pdf.tmp` normally only exists for a short amount of time (while building).
It excludes following build-related files:
*   `build/priv-isa-asciidoc.pdf.tmp`
*   `build/unpriv-isa-asciidoc.pdf.tmp`

Add `*.pdf.tmp` to build/.gitignore

---

src/colophon.adoc
src/zfa.adoc

While looking at some Zfa patches I couldn't actually find a concrete reference to the spec being frozen, just the commit text of the binutils patches.  I figured this was the easiest way to ask...

Mark Zfa as Frozen and Version 1.0

---

src/rv-32-64g.adoc

This is a subset of #1094 and an AsciiDoc port of #862.

Add OP-V to base opcode map (AsciiDoc port)

---

src/m-st-ext.adoc

I think this was obviously in the writers' intent that only nonzero results have the same sign as the dividend. The non-normative note is also updated to reflect the special case of signed division overflow.

Clarify REM wording

---

build/Makefile

`ASCIIDOCTOR_OPTS` are recycled for html output as well, but it seems to not blow up.
closes #1124

apply compression for adoc pdf outputs

---

src/hypervisor.adoc
src/machine.adoc
src/rv32.adoc
src/supervisor.adoc

Based on casual grepping, we omit the hyphen in 46 cases but retain it in 7.  Standardize on the more common one.

Standardize on no hyphen in illegal instruction exception

---

src/colophon.adoc
src/counters.adoc
src/f-st-ext.adoc
src/hypervisor.adoc
src/intro.adoc
src/machine.adoc
src/priv-csrs.adoc
src/rv32.adoc
src/rv64.adoc
src/supervisor.adoc
src/zicsr.adoc
src/zimop.adoc

Reverts #1131 
One might argue that "illegal instruction" is a compound noun in the context of computer architecture, and so hyphenating "illegal instruction exception" would not be necessary.  But there are certainly other noun phrases we use as exception types where the hyphen would be mandatory.  This scheme is also friendlier to readers, since it provides explicit phrase grouping.  So, standardize on hyphenation.
Also, fix a couple places where "trap" was used where "exception" was more appropriate.

Hyphenate "virtual-/illegal-instruction exception"

---

src/m-st-ext.adoc
src/naming.adoc

Zmmul is defined to be a subset of M. It follows that M implies Zmmul. This closes https://github.com/riscv/riscv-isa-manual/issues/869. It also resolves a question raised in the Toolchains SIG: https://github.com/riscv-non-isa/riscv-asm-manual/issues/91#issuecomment-1714090713.
This PR adds this implication to a table in the "ISA Naming Conventions" chapter. (EDIT: and also in the M chapter.)

M implies Zmmul

---

src/machine.adoc
src/priv-preface.adoc

Even though one can say that WFI is a hint to the implementation, it is not a HINT in the RISC-V sense of the term, so avoid the word hint to avoid confusion.

Don't describe WFI as a hint

---

src/machine.adoc
src/supervisor.adoc

1. Extend the >XLEN decomposition relaxation to vector stores by deleting the word “floating-point” in the description of PMP faults.
2. Add similar text copied from the PMP section to the Sv32 section for virtual memory page faults.
> This is just a clarification, since it follows logically from misaligned accesses possibly being decomposed into smaller accesses.
> "Notably, instructions that reference virtual memory are decomposed into multiple accesses."

Allow Misaligned Stores with Page Fault to partially succeed

---

src/resources/riscv-spec.bib

Changed 'Computur' to 'Computer' for accuracy.

Fix journal name typo

---

src/hypervisor.adoc
src/machine.adoc
src/priv-preface.adoc
src/supervisor.adoc

This PR is incomplete, as @ved-rivos and @gfavor are supposed to provide some non-normative text that describes the intended function of this exception.
cc @jhauser-us

Define hardware error exception cause code

---

src/machine.adoc

Drop notes on obsoleted user-mode software interrupts   
Resolves #1158

   delete user-mode interrupt notes in mtvec register section

---

src/machine.adoc

Fix MODE field description in the mtvec register
In Section 1.6, "Exceptions, Traps, and Interrupts" of the unprivileged specification, a distinction is made between exceptions and interrupts.
Table 13 in the privileged specification uses the term "exceptions" as a catch-all expression, encompassing both "exceptions and interrupts" which may not be immediately apparent.
Reading "exceptions" merely as "exceptions" while seeing following word "interrupts" can led to believe that the 0th bit is used to control exception handling behavior, while the 1st bit is used to control interrupt handling behavior.

Fix MODE field description of mtvec register

---

src/supervisor.adoc

It appears that during the conversion from Latex to asciidoc, the 4 KiB divisor for the satp description was dropped. This commit brings it back.

Specify that the supervisor physical address is divided by 4 KiB

---

marchid.md

Last PR I made was apparently on the wrong branch, whoops.
I have recently released my RISC-V core and as it passes the RISC-V unit tests, I think it's time to apply for an marchid value.
If this PR is merged, I will set the value of marchid in my core to 37 (or whatever value ends up being merged).
My CPU and it's testing environment can be found here:
https://github.com/robotman2412/boa-risc-v

Add marchid for Boa-RISC-V (on the correct branch this time)

---

marchid.md

I've finally tested fully my RISC-V core and i think it's type to apply for a value of marchid.
I've released my first version WIV64 and created the script for automated testing.
If you want to try the tests just:
- Install `verilator`
- Install `riscv64-unknown-elf-gcc`
- Configure `cmake` and build it
- Run `./test.sh`on the main directory
The actual release:
[WIV64 1.00](https://github.com/StartForKiller/WivCPU/releases/tag/v1.00)
I've used `marchid` `38` as a temporary value, awaiting the approval

Add marchid for WIV64

---

src/hypervisor.adoc
src/priv-csrs.adoc

Attempts to access non-existent CSRs are reserved

---

marchid.md

For the cases where QEMU isn't pretending to be something else (for example, when targeting a virtual platform) it'd be nice to set the arch IDs to something other than 0.  That way users can detect they're running on QEMU and act differently, in case they want to work around a QEMU issue of some sort.
Link: https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/arch-riscv64/dynamic_function_dispatch.cpp#47
Link: https://lore.kernel.org/r/20240131182430.20174-1-palmer@rivosinc.com/

Add a QEMU architecture ID

---

src/machine.adoc

relates to https://github.com/riscv/riscv-isa-manual/pull/1105#issuecomment-1709489922
@aswaterman @gfavor

Hardware Error exception priority

---

src/riscv-unprivileged.adoc
src/rv-32-64g.adoc
src/zawrs.adoc

This PR integrates the Zawrs specification into the Unprivileged spec.

Zawrs - Wait-on-Reservation-Set chapter integration.

---

src/a-st-ext.adoc

Since PTE updates are specified to occur as a result of "memory accesses" it is possible to interpret the old wording as requiring no PTE update for a failed SC, since there is no memory access.  However, the PTE update is part of the translation process, which on natural implementations will occur before the reservation validity check can occur.
This is consistent with the wording in "Addressing and Memory Protection" which allows traps to prevent the memory access without preventing the PTE update.
(Filing this in a dedicated issue so it can be considered for 1.13.)

Explicitly allow side effects for a failed SC

---

.github/workflows/merge-and-release.yml

This commit introduces a new GitHub Action designed to automatically release a new ISA version following the merge of each pull request. This enhancement ensures the ISA remains consistently updated, particularly after the integration of new extensions through PRs.

Add new Action to Release a new ISA when merging a PR

---

marchid.md

`marchid` 42 allocation request for Coreblocks. It is an experimental, modular out-of-order RISC-V core generator.
Repository link: https://github.com/kuznia-rdzeni/coreblocks

Add marchid for Coreblocks

---

src/images/bytefield/mncause.edn
src/rnmi.adoc

This is a backwards compatible change to support resumable double traps within M-mode when both extensions are implemented.  Although the resumability feature is not terribly interesting, the reuse of the Smrnmi state for M-mode double traps aids debugging (and fault diagnosis for the hardware-error exception case).

Update Smrnmi to account for Smdbltrp extension

---

src/zawrs.adoc

Replace 'Statndard' with 'Standard'.

Fix typo in Zawrs title

---

src/v-st-ext.adoc

The changes are:
- Clarify that vsetvl[i] x0,x0 is reserved when `vill` was 1 beforehand.  This was discussed on the following mailing-list thread: https://lists.riscv.org/g/tech-vector-ext/topic/94729185#846
- Relax tail/mask policy to agnostic for mismatched source/dest EEW.  This was discussed on the following mailing-list thread: https://lists.riscv.org/g/tech-vector-ext/topic/94729097#845
As mentioned on the relevant threads, implementations that conform to RVV 1.0 are compatible with these changes.

Incorporate two fixes to RVV 1.0 spec

---

src/v-st-ext.adoc

This PR is identical to https://github.com/riscv/riscv-v-spec/pull/917 . Please see conversation there.

Clarify slide semantics

---

src/b-st-ext.adoc
src/machine.adoc
src/naming.adoc

Should wait for ratification prior to merge.
Integrates text from: https://github.com/riscv/riscv-b/blob/main/b.adoc

Integrate B standard extension text

---

src/vector-crypto.adoc

This table used sm3me instead of vsm3me

Add missing v to beginning of extension name in vector-crypto.adoc

---

src/smcdeleg.adoc

Set an explicit anchor on the Indirect HPM State Mappings table and update link to it further down in the document.
This fixes https://github.com/riscv/riscv-isa-manual/issues/1291

Set explicit anchor on table.

---

src/machine.adoc

There was a missing reference to Figure 16. Fixes https://github.com/riscv/riscv-isa-manual/issues/1294

Fix reference to menvcfgreg

---

src/sstc.adoc

The second to last paragraph starts "When STCE in menvcfg is zero, ...".  This should be clarified to say "When this extension is implemented and STCE in menvcfg is zero, ...".  And ditto for the beginning of the last paragraph.

Sstc editorial fixes.

---

src/cmo.adoc

Adding *tval address explanation text.  This is Issue #1317.

Adding *tval address explanation text.

---

src/rv-32-64g.adoc
src/vector-crypto.adoc

Resolves #1310
This major opcode is currently used by vector crypto extensions.  It'll likely be used by future vector extensions, as well.
The official naming table currently describes this opcode as _reserved_, which is obviously no longer the case.  Informally, it has sometimes been referred to as OP-P, since there was once a plan to encode the packed-SIMD extensions there.  That plan has been superseded by a proposal to use brownfield space elsewhere.
The vector crypto spec reflects the informal usage of OP-P; this PR fixes that up, too.

Opcode 0x77 is named OP-VE, for "Vector Extensions"

---

src/hypervisor.adoc

Fix typo in hypervisor.adoc

---

src/scalar-crypto.adoc

In `Zkt` description of covered crypto bitmanip extensions: `zbkx` is repeated twice and `zbkc` is not mentioned (although `clmul` and `clmulh` are listed below as part of `Zkt`)

[scalar-crypto] fixing typo in bitmanip extension list in zkt

---

src/c-st-ext.adoc

Fixes #1332 where RV6 s/b RV64.
Fixes #1333 where LDSP s/b LQSP.
Fixes #1334 where SQSW s/b SQ.

Typo fixes.

---

src/resources/themes/riscv-spec.yml
src/sscofpmf.adoc
src/sstc.adoc

Fix heading spacing in theme and delete redundant use of .Non-normative before some notes.

Fix heading spacing

---

src/hypervisor.adoc

Note that this is currently the initial change.
It does not replace other references to
*   *the hypervisor extension* to
*   *the "H" extension*.
Still, even without replacing those, it can be a first patch of the series.
- "Standard Extension for Hypervisor Support" is the official name (as [suggested](https://github.com/riscv/riscv-isa-manual/pull/1084#issuecomment-2026107589) by @aswaterman)

Officially name the hypervisor extension "H"

---

src/colophon.adoc

I noticed that this piece of formatting code was introduced in `15322920b281458a100a6375262d6516e8671a45`, and then it looks very strange in `unpriv-isa-asciidoc.html`. I feel like it should be written incorrectly.
In https://github.com/riscv/riscv-isa-manual/releases/download/20240411-riscv-isa-release-DRAFT/unpriv-isa-asciidoc.html
```
The "Zam" extension, which permits misaligne%autowidth,float="center",align="center",d AMOs and specifies their semantics, has been defined.
```

Removal of Erroneous Attributes

---

src/colophon.adoc

Reverts riscv/riscv-isa-manual#1354 - change broke doc build.

Revert "Removal of Erroneous Attributes"

---

build/Makefile

Without this change I get the following error:
`docker: Error response from daemon: create .: volume name is too short, names should be at least two alphanumeric characters.`
After fixing that by using `pwd`, I get the following (the w flag is added due to `-C build`): `make: *** No rule to make target 'w'` Fix this by using -$(MAKEFLAGS). I confirmed that both `make -C build docker -j4` and `cd build && make docker -j4` work.

Fix running `make -C build docker`

---

src/machine.adoc
src/supervisor.adoc

More register name fixes - https://github.com/riscv/riscv-isa-manual/issues/1352

More register name clean up

---

src/indirect-csr.adoc

Fixes issue #1367 setting register name as monospaced in non-normative text and italicizing and bolding the trailing variable.

Fixing italics issue.

---

marchid.md

This PR assigns ID 45 to rrv32, because that is the next `marchid` in line. If permissible, I would prefer to use 1495879317 instead. This larger ID encodes a memorial to my father, who passed away 13 months ago. He set and guided me on the 25-year path that led to the creation of rrv32. That ID still has the high bit unset, which means it is technically within the open source `marchid` space. (However, I could easily see such a huge ID being inconvenient and annoying for those who want to make a simple lookup table for `marchid` values.)

Add marchid for rrv32

---

src/colophon.adoc

Fixes the bolding of extension names in the "what's included" table in the Preface.

1394 formatting issues in version 20240411

---

src/intro.adoc
src/machine.adoc
src/supervisor.adoc

Represent them as never-accessible main memory or I/O regions instead.

Remove "vacant" class of memory region

---

build/Makefile

This pull request fixes `docker` Makefile rule to allow building EPUB manuals.

Fixed Makefile to allow building EPUB manuals with docker rule

---

src/zc.adoc

The c.zext.h prerequisites and operation were duplicated at the end of the c.sext.b section.

Remove c.zext.h prerequisites and operation from c.sext.b

---

src/zawrs.adoc

Stating the WRS.* instructions are not supported in constrained LR/SC loops is superflous as the constrained LR/SC loop specification precisely identifies the supported instructions.

remove superflous constrained LR/SC statement from zawrs chapter

---

src/b-st-ext.adoc

- Remove heading stating "Bit-manipulation a, b, c and s extensions grouped for public review and ratification"
- Slightly reword intro to remove mention of lack of a larger extension now that B is ratified

Update B extension description to remove mention of sub extensions grouped for review

---

src/cmo.adoc

Define access size to be size of cache block for PMP/PMA checks

Clarify CBO access size

---

src/machine.adoc

- move title before the table
- replace redundant FS by VS

machine.adoc: fix table title

---

src/intro.adoc
src/rvwmo.adoc

This pull request addresses the following issues:
- https://github.com/riscv/riscv-isa-manual/issues/1403 - Incorrect table numbering due to hard-coded table numbers in unprivileged spec manual
- Reference symbols in intro now match the style used in other tables in the doc (explanation of symbol is below table, not in table description)
- asciidoctor error due to the incorrect number of columns specified in `cmo.adoc`

Table Fixes

---

src/smstateen.adoc

The original expression of this sentence is ambiguous.  According to 'Parter 2.5 Access control by the state-enable CSRs' in The RISC-V Advanced Interrupt Architecture Version 1.0, bit 59(AIA) in stateen controls access to all other state added by the AIA and not controlled by bits 60(CSRIND) and 58(IMSIC).But “is not controlled by either the CSRIND or the IMSIC bits of mstateen0“ seems more like it's restricting "the AIA bit" rather than "state".

Correct typos

---

src/hypervisor.adoc
src/mm-formal.adoc
src/scalar-crypto.adoc
src/vector-crypto.adoc
src/zc.adoc

There are a couple of classes of misuse of "pseudo" within the document that conflict with uses elsewhere in the overall RISC-V ISA Specification:
1. All uses of "pseudo-ops" should instead be "pseudoinstructions".
1. "pseudosomething" sometimes has a space or hyphen separating "pseudo" from the rest of the word. We should pick one usage. I think the most common is with no separation. "pseudorandom" is in the dictionary, as an example.

Make uses of 'pseudo' consistent

---

Makefile

Fix bugs introduced by #1449:
- dependency tracking was broken; running `make` twice in a row would rebuild everything.
- EPUB build was broken because the UTF-8 charset was not explicitly specified.
@wmat please keep me in the loop on build-system changes going forward.

Fix build-system bugs

---

src/extending.adoc

The 'L' and 'T' extensions were placeholders but later removed.
Most changes were done by https://github.com/riscv/riscv-isa-manual/pull/655.
So the sentence here should be adapted as well.
Otherwise it would cause confusion for a new hand.
Because 'L' and 'T' extensions are neither complete nor planned standard extensions now.

Update extending.adoc to delete extension name 'L' and 'T'

---

src/images/bytefield/rvc-instr-quad1.adoc

This patch fixes an error in the instruction listing tables for the C extension. The definition of the C.NOP instruction specifies that using an immediate other than zero encodes a hint. The table was wrongly stating the opposite: that a zero immediate encodes a hint.

Fix C.NOP hint condition

---

src/b-st-ext.adoc
src/scalar-crypto.adoc

Deleted duplicate data from Scalar Crypto chapter and added xrefs to the content in the Bitmanip chapter.
Fixed up the IDs and alternate text in the Bitmanip chapter.

Consolidates Zbkb, Zbkc, and Zbkx into he Bitmanip chapter.

---

src/b-st-ext.adoc
src/scalar-crypto.adoc

Related to https://github.com/riscv/riscv-isa-manual/issues/1518
- synced contents of xperm4,xperm8,brev8 but didn't combine them yet
- consistent internal labels, function names
- misc typos. xprem8 -> perm8,  removed -rc4 from versions, apparent bug in xperm8 sailcode (called xperm_n)

Cleanup for of XPERM4, XPERM8, BREV8  ( https://github.com/riscv/riscv-isa-manual/issues/1518 )

---

src/images/wavedrom/c-integer-const-gen.adoc

For C.LUI, imm[16:12] should be nzimm[16:12].  This matches the LaTeX spec and was a typo.

Typo change imm to nzimm.

---

src/hypervisor.adoc
src/naming.adoc

Typos fix in naming.adoc and hypervisor.adoc

---

src/hypervisor.adoc

This partially reverts commit 7880c719c1331eb6951baadeb20f442a7bb214c6.
"X need only be Y" is grammatically correct.

Partially revert "Typos fix in naming.adoc and hypervisor.adoc"

---

src/rv32.adoc

These non-normative clarifications were made in response to architecture review of the semihosting spec.

Add notes about semihosting NOPs; clarify there is only one semihosting exit NOP

---

src/hypervisor.adoc
src/priv-preface.adoc

This matches what the sstatus.MXR field definition already says: it affects loads, rather than reads.
Resolves #1061
cc @elithist

Clarify that MXR affects explicit memory accesses only

---

src/scalar-crypto.adoc

Write-only accesses are legal (though not useful).
See https://github.com/riscv-software-src/riscv-isa-sim/issues/1728

Clarify that only read-only accesses to the seed CSR are forbidden

---

src/rv32.adoc

Symmetric with defining J pseudoinstruction earlier in the same section.
Resolves #1253

Define JR, RET pseudoinstructions

---

src/scalar-crypto.adoc

Original text: "A wfi ot pause mechanism..."
The 'ot' should be changed to 'or'

[scalar-crypto] Fix typo issue

---

src/unpriv-cfi.adoc

This doesn't change the meaning of the pseudocode because "raise" is presumably a terminal statement, but it makes the code easier to read.
h/t @tsaiyenting

Add missing "else" in SSAMOSWAP pseudocode

---

.github/workflows/isa-build.yml
.github/workflows/merge-and-release.yml

GitHub Actions runners are multicores; take advantage of that.

Parallelize the CI builds

---

src/hypervisor.adoc

I forgot to change this typo mentioned by @somyadashora in #1550 in last PR, sorry for that.

Fix Typos on hypervisor.adoc

---

src/bfloat16.adoc
src/zfinx.adoc
src/zimop.adoc

This fixes the few instances of "requires" I found in the spec.
References:
https://github.com/riscv/riscv-v-spec/issues/723#issuecomment-949542444
https://github.com/riscv/riscv-v-spec/commit/e8594a7b9f4c22d3c02e2cdf81ad5db8d0bb8c01
https://github.com/riscv/riscv-isa-manual/blob/399c9a759eb4540a65c60e2cc236164821ff2346/src/naming.tex#L46
cc @aswaterman

Use standard "depends upon" verbage rather than "requires"

---

src/riscv-unprivileged.adoc
src/scalar-crypto.adoc

Moving references from titles as they break section numbering and the TOC.  Moved the reference beneath the title it was in.
See section 34.8.3.1, 34.8.3.2, 34.8.3.3, and 34.8.3.4

Remove references from titles.

---

Makefile

Podman is a Docker replacement, which is developed by RedHat and available on related Linux distributions (e.g. RHEL or Fedora).  Podman differs from Docker in several security-related aspects.  One of them is, that Podman requires poper SELinux labels on volume content mounted into a container. This difference to Docker results in the following error when building the specification:
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
/var/lib/gems/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/cli/options.rb:238:in `stat': Permission denied @ rb_file_s_stat - src/riscv-privileged.adoc (Errno::EACCES)
from /var/lib/gems/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/cli/options.rb:238:in `block in parse!'
from …
```

Makefile: Add implicit SELinux labels when using podman

---

src/machine.adoc

Apparently, values in the first column were not specified when several rows were added to the table.
Right now, this table looks like this:
<details>
</details>

Add missing values to mepc values table

---

src/smcdeleg.adoc

Fix bug, only get VIE on VS-mode reads, not VS-mode writes (which get IIE)

Fix scountovf exception behavior in smcdeleg.adoc

---

src/intro.adoc

In section "1.3. RISC-V ISA Overview," chapters 6 and 8 are mentioned when they should have been 3 and 5, respectively. They are referenced differently from other chapters. Unlike other chapters, these have an explicit title. This modification can break the text with future changes. I don't know if this is on purpose. 
Please look into it. 
Thank you.

Update intro.adoc: Missreferenced chapters

---

src/c-st-ext.adoc

It's an inclusive range, and it should have a space after the comma.
Fixes #1633

Fix range representation for C.ADDI16SP immediate

---

src/images/wavedrom/b-immediate.edn
src/images/wavedrom/i-immediate.edn
src/images/wavedrom/j-immediate.edn
src/images/wavedrom/s-immediate.edn
src/images/wavedrom/u-immediate.edn
src/rv32.adoc

This separates the immediates into separate wavedrom files which allows us to add the caption to the last immediate on the page (j-immediate) which puts it after the grouping of wavedroms correctly.

Separate immediates into separate wavedrom files.

---

src/b-st-ext.adoc
src/scalar-crypto.adoc

Something went wrong when these specs were integrated into the main ISA manual.  This PR restores the definitions of these instructions to the ratified ones.
Resolves #1632

Fix descriptions/encodings of zip/unzip instructions

---

Makefile

If you have real Docker (not Podman) then by default it will run everything as root, so your build directory is owned by root and the Makefile will not work at all because it tries to modify the build directory.
This adds a flag so that Asciidoctor runs as the current user in Docker instead of root.

Run docker as the current user

---

src/hypervisor.adoc
src/machine.adoc
src/resources/riscv-spec.bib
src/riscv-privileged.adoc
src/supervisor.adoc
src/zpm.adoc

This PR adds pointer masking to the privileged ISA manual. It is based on version 1.0-rc3 (frozen):
https://github.com/riscv/riscv-j-extension/releases/tag/pointer-masking-v1.0.0-rc3

Add pointer masking to the privileged ISA manual.

---

src/unpriv-cfi.adoc

The Zicfiss extension add two amo instructions that are outside of the Zimop / Zcmop encoding space
Correcting the Statement so there is no ambiguity.

change ambiguous statement in cfi section

---

src/smcntrpmf.adoc
src/sscofpmf.adoc

Adds back bits 57 & 56 to Sscofpmf and Smcntrpmf.  @gfavor and @bcstrongx , can you please make sure I added these bits back correctly?

Adds back bits 57 & 56

---

Makefile

Reapplication of 3539eff338352aba83dbae9e7b310d6a7d9a7d56 but this time we only add the `--user` argument for root Docker. Rootless Docker behaves the same as Podman and doesn't need the `--user` flag; in fact it breaks builds if you add it.
I also added a comment for the `:z` flag.

Run root Docker as the current user

---

src/priv-csrs.adoc

While it is always a guest physical address for the hypervisor
traps, when used by a double trap it holds an mcause value.
Change the description to "second trap value" to match the description
used in the section heading. While touching this line also sync the
description of the other CSRs in this part of the table as well as the
*tval registers for the other privilege levels.

Update description of mtval2 in CSR table

---

src/machine.adoc

...because it's an unprivileged concept.  Also, in mixed-XLEN environments, the weaker constraint should prevail, the less-privileged environment doesn't even know about MXLEN.

In MAG definition, use XLEN rather than MXLEN

---

src/zpm.adoc

Adding a non-normative comment to clarify a question about the interaction of pointer masking with other portions of the privileged spec. See here for the original discussion:
https://github.com/riscv/riscv-j-extension/issues/84

Add a non-normative comment to clarify MXR behavior for pointer masking.

---

src/b-st-ext.adoc

The defn of zext.w still exists in the add.uw section.
See #1321

Remove pseudoinstructions from B instruction table

---

src/supervisor.adoc

Add NOTE that only G-stage PBMTs apply to VS-stage PTE accesses

---

src/unpriv-cfi.adoc

remove redundancy for rd == x0 in def of return
This cosmetic fix was suggested here: https://github.com/riscv/riscv-cfi/pull/229

remove redundant 'rd == x0'

---

src/c-st-ext.adoc

Table "Compressed 16-bit RVC instruction formats" header indicating the bits corresponding to each column only aligns properly with the first row (CR format), but doesn't reflect the boundaries of other rows (for example, funct3 or rs1'), making it hard to read.
This PR fixes that by distributing the bit indexes on the table header across the "actual" table columns (unmerged cells), so that it's clear which bits each field spans in every compressed instruction format, not just CR.
This is a really minor stylistic edit that you may want to squash into a future commit (or even just apply the change manually in a future edit).

Improve table: Compressed instruction formats

---

src/f-st-ext.adoc

Fix NOTE about ARM FMA mnemonics

---

src/priv-preface.adoc

@aswaterman - the table lists extensions in two forms. Some are listed with " Extension" following the extension string and others with just the extension string. Is one preferred? If so I can update the remaining rows to the preferred form in this PR as welll.

Add Ssqosid to extensions table in preface

---

src/v-st-ext.adoc

In a similar vein to https://github.com/riscvarchive/riscv-v-spec/commit/856fe5bd1cb135c39258e6ca941bf234ae63e1b1, this note states that compilers don't need to "know or change vtype" for whole vector register moves.
There's some truth to this in that compilers can largely ignore SEW and LMUL, but ultimately they do depend on vtype and the current wording might be misleading. A compiler may in fact need to change vtype to clear vill, see: https://github.com/llvm/llvm-project/issues/114518

Clarify note that compilers may need to change vtype for vmv<nr>r.v

---

src/supervisor.adoc

Someone familiar with the interrupt handlers of other ISAs may incorrectly imagine that the current description means that RISCV cores will automatically perform the swap of `sscratch` with a user register.
This is not the case: it is a recommendation disguised as a description. Flesh it out a bit so it is less ambiguous.

Explain `sscratch` is only swapped by software

---

Makefile
src/riscv-privileged.adoc
src/riscv-unprivileged.adoc

This avoids writing output files into the source tree by changing the imagesoutdir variable to point at the build tree. We can bind mount source and docs-resources as read-only into the build directory and then create symlinks to ensure the docker container sees the appropriate directory layout.
Note: imagesoutdir must be an absolute path since otherwise asciidoctor-mathemtical interprets it as a path relative to the source dir rather than the current working directory (asciidoctor-diagram does the expected thing and interprets it relative to the cwd).

docker: mount source and resources as read-only

---

src/mm-eplan.adoc

In the latest unprivileged version, there is a bug in Figure 4 of A.3.3. Atomicity axiom.
The wrong picture is as follows:
The right picture should be:
Fix it.

[RVWMO Explanatory] Fix the figure used to illustrate atomicity axiom rule

---

src/sstc.adoc

This may have been true once but it doesn't appear to be the case now.
Fixes #1732

Remove outdated statement that Sscofpmf is written as a diff

---

src/supervisor.adoc

When the zicfiss extension is present and we have both a superpage misaligned and a shadow stack enforcement failure we want to report the misalignment as it is a recoverable error and  misaligned superpages logically happen before permission checks (there is no need to know the access type of the transaction check logically happens in the PTW)
> [!NOTE]
> even if we swap the former point 6 and point 5 this change doesn't affect previous systems as the reported errors were both page-faults

Clarify the shadow stack enforcement against superpage missaligned check

---

src/smstateen.adoc

In newest [Release riscv-isa-release-f3f8a93-2024-11-28](https://github.com/riscv/riscv-isa-manual/releases/tag/riscv-isa-release-f3f8a93-2024-11-28) , the figures of `mstateen0` and `hstateen0` is incorrect, missing `SE0` field.

fix field pattern of CSR mstateen0 and hstateen0 in smstateen

---

src/cmo.adoc

Fixes #1759. These changes have been incorporated into the priv manual so the note is no longer relevant or accurate.

Remove Outdated  CMO CSR note

---

src/vector-examples.adoc

Improves accuracy of vector division approximation example.
The previous implementation was unnecessarily inaccurate:
```
Measured max error of 2.465257280 ulp @ (1.2449559e-01, 5.2960633e+36)
func (0x1.fdef16p-4, 0x1.fdfe0ap+121) = 0x1.fff0f8p-126
func_ref (0x1.fdef16p-4, 0x1.fdfe0ap+121) = 0x1.fff0fcee3633cp-126
4'550'824'890 tested in [0 ; inf] x [0x1.000008p-128 ; 0x1p126]
68.8976110218998059% correctly rounded  (  3135409631)
92.7973265084255985% faithfully rounded (+ 1087634201)
7.2026734915744033% >= 1.0 ulp         (+  327781058)
```
Which is 21.7 bits of precision rather than the claimed 23.
The new implementation has lower maximum error and higher correctly-
and faithfully-rounded rates:
```
Measured max error of 1.493816005 ulp @ (5.0745111e+02, 4.9807361e-01)
func …
```

Improves accuracy of vector numerical examples

---

src/c-st-ext.adoc
src/rv32.adoc
src/scalar-crypto.adoc
src/smctr.adoc
src/unpriv-cfi.adoc
src/v-st-ext.adoc
src/zpm.adoc

Restore semicolons removed accidentally in aaad788afe0019ebb5c63d3c3193e9d951c3f3e0

Fix wording and formatting of x0 special cases

---

.github/workflows/check-ready-to-merge.yml

Check if can be merged based on the tag set. In this case, PRs with Pending Ratification cannot be merged.

Check Mergeable by Label

---

src/rv32.adoc

I don't understand how those XLENs even got there.

Fix formatting in "RISC-V base unprivileged register state" table

---

src/images/wavedrom/mseccfg.edn

Machine ISA says that PMM field is furnished by the Smmpm extension. However `mseccfg` CSR definition is missing `PMM` field. This commit fixes that.

mseccfg: Add PMM field in mseccfg CSR

---

src/cmo.adoc

Rework the text to be much more explicit about the behaviour when rs1 is not aligned to the cache block size.
I also moved & slightly reworded the note about the assembly syntax since it's not relevant to the instruction semantics.
Fixes #1263

Clarify CBO for unaligned rs1

---

src/rv32.adoc
src/rv64.adoc

See discussion on https://lists.riscv.org/g/tech-unprivileged/message/968 and https://groups.google.com/a/groups.riscv.org/g/isa-dev/c/MudQz5KF78I/m/zII13eWIAAAJ

Designate semihosting entry/exit HINTs as standard, not custom

---

Makefile

This patch adds a check that the cloning operation was done properly, with the submodule. If that check fails, it will print a message and then do the proper git submodule command so that the docs-resources/ submodule and any other submodules are properly checked out. If desired, the git command could be removed and it could just print the command to invoke -- I'm open to feedback on that.
The phony target `submodule-check` is only added as a dependency on the build, build-container, and build-no-container targets, which should suffice for most oops-forgot-submodule mistakes.

Added submodule check

---

src/mm-formal.adoc

The alloy tool for specifying the formal memory model has been updated to [version 6](https://alloytools.org/alloy6.html). The single quote has been introduced as a new operator, so the old notation no longer compiles. This ensures the formal memory spec still works under the new alloy 6.

fix: alloy6 language migration

---

src/machine.adoc

Repeated parentheses were not escaped, so they were not displayed correctly.

Fix parentheses in mstatus SD description

---

src/c-st-ext.adoc
src/intro.adoc
src/mm-formal.adoc
src/scalar-crypto.adoc
src/zpm.adoc

Always use the `<<section-reference>>` style instead of writing a particular number, since the number will become incorrect before your next breath.
For scalar crypto, this resulted in some stylistic changes and removal of outdated contextual information (e.g. references to the never-ratified `grevi` bit-manipulation instruction).
In most other cases, the changes were mechanical.

Fix hard-coded section references

---

src/machine.adoc
src/mm-formal.adoc
src/scalar-crypto.adoc
src/v-st-ext.adoc

Writing `Section <<sec-foo>>` results in text like "Section Section 11.6".

Remove redundant "Section" words

---

src/vector-crypto.adoc

The list of extensions that include Zvknhb and Zvbc (and therefore require support for SEW=64) was incorrect.  Fix it.

Fix list of vector crypto extensions that require SEW=64

---

src/a-st-ext.adoc

Most of the series moves non-normative text into notes, but the last patch also removes page breaks before examples as I found it hard to read otherwise.
It doesn't bring the ISA manual any closer to being ISO worthy, but I hope it'll at least be easier to understand until then.
I stumbled upon this issue thanks to https://github.com/riscv/riscv-isa-manual/issues/1814 and tried hard to avoid any controversial changes.

Move non-normative parts of "A" extensions (atomics) into NOTE block

---

src/rv32.adoc

I think that opcode change here makes it clear enough that FENCE instruction requires  `fm=0000 ` and given the previous wavedrom, I also think it is clear that there is room for further future uses.
@ThinkOpenly @aswaterman Do you think I should clarify the difference between Category vs Instruction more clearly?
Resolves #1782

Fetch Instruction/Category clarification

---

src/v-st-ext.adoc

After reading through the RVV spec, I found "vector start position" unclear with what it refered to.
Thanks!

vstart definition clarification

---

src/counters.adoc

The included commit, which added some non-normative text to the Zicntr chapter, was inadvertently dropped when resolving merge conflicts that arose from #1215.  Restore it.  See #1113.

Fix merge conflict introduced by #1215

---

src/m-st-ext.adoc

This PR contains changes for the style guidelines that were discussed in the doc-sig. Style guidelines say that extension names and registers, among others should be in back ticks. 
This also fixes the old spelling of "implementors".
One thing to discuss is the code sequences. Because they are code sequences, I put the pieces into back ticks to indicate code, as you can see if the following section:
`MULH[[S]U]` `rdh`, `rs1`, `rs2`; `MUL rdl`, `rs1`, `rs2` (source register specifiers must be in same order and `rdh` cannot be the same as `rs1` or `rs2`).
but I can be convinced otherwise.

Applying style guidelines and spelling to M

---

src/zifencei.adoc

Change imm[11:0] to funct12 in FENCE.I

---

src/machine.adoc

This has long been the intent, but the spec didn't make this especially clear.
The proposed resolution is to clarify that these bits are writable, which is maximally inclusive of both classes of implementations: those that choose to hardwire the bits and those that choose to make them writable.
Resolves #1837

Clarify that misa.S and misa.U are optionally writable

---

src/rnmi.adoc

(As opposed to UNMIs.)
Now, all references to "NMI" in this chapter are fully qualified.
Fixes https://github.com/riscv/riscv-debug-spec/issues/1107#issuecomment-2667488240

Clarify that the NMIs referred to in the RNMI spec are RNMIs

---

src/bfloat16.adoc
src/vector-crypto.adoc

Addressing https://github.com/riscv/riscv-isa-manual/issues/1877
Clarifying dependencies structure for `Zvfbfmin` and the vector crypto extensions.

[#1887] clarifying Zvfbfmin/vector-crypto extension dependencies

---

src/hypervisor.adoc

Passive vs. active voice issue.
See https://github.com/riscv-software-src/riscv-isa-sim/issues/1928#issuecomment-2702746508

Clarify that hgatp field zeroing is software's responsibility

---

src/v-st-ext.adoc

The part about the trailing "b" being required is true, but I'm not sure it provides any value in this section.

Remove note that the Zvl*b extension names may change.

---

src/vector-crypto.adoc

The Sail code for `vror.vi` uses `imm` instead of `uimm`,  even though "uimm" is specified in the encoding.  
A correct reference is `vwsll.vi`, which properly uses `uimm`.
Please cross-check the correctness of this proposed change.

Change VROR_VI immediate field from imm to uimm

---

marchid.md

This Pull Request adds the CVA5 core that is part of openhw group.

reserving marchid 48 for CVA5

---

.github/workflows/isa-build.yml
README.md

This makes it easier to view the latest snapshot without having to download a
PDF from the releases page.
I've deployed this to my github fork, so it will look as follows once deployed:
- [Unprivileged spec](https://arichardson.github.io/riscv-isa-manual/snapshot/unprivileged/).
- [Privileged spec](https://arichardson.github.io/riscv-isa-manual/snapshot/privileged/).
The HTML is deployed to a snapshot/ subdirectory to make it possible to also
deploy versioned releases in the future.
This has been very useful for the CHERI spec so far (https://riscv.github.io/riscv-cheri/). In the CHERI spec I added a warning at the top of the document that it is not a valid release:
> This document is a specification snapshot built from github.com/riscv/riscv-cheri/commit/cf51732e0bf6b2775516d168642f05dcca …

Deploy a snapshot of the specification to GitHub pages

---

src/supervisor.adoc

This got out of sync due to steps added in #1742.
Also fix an unrelated typo.

Fix a step reference for Sv32 address translation.

---

src/smcntrpmf.adoc

Fixes Issue: #1933 
Fixes: 1929d45a059979c55b070fba414d97d530a44c99
Author: mmoizhussain
On branch mmhus/fix-smcntrpmf-heading
Changes to be committed:
modified:   src/smcntrpmf.adoc

[#1933] Fixed Smcntrpmf heading not showing up in riscv-privileged.pdf

---

Makefile

Setting UNRELIABLE_BUT_FASTER_INCREMENTAL_BUILDS=1 on the make command line
will avoid wiping the entire build directory before builds. Since each
output file uses a different build directory there should be no
need to wipe the whole build directory. The Makefile already triggers a
rebuild if any file under the source directory is modified so this should
be safe.
This significantly speeds up the build for me since we no longer regenerate
all the diagrams for each build. For the unprivileged manual the build time
goes from about 4:30 to 3:40.
However, it has been shown that non-clean builds don't always produce the
same output PDF, so this is gated by an opt-in flag.

Add a flag to allow faster (but unreliable) incremental builds

---

src/a-st-ext.adoc

This PR fixes an editing error in which "C" should have been changed to "Zca" when the various Zc extensions were incorporated.  It also clarifies that any compressed instruction, not just those in Zca, that map to one of the permitted "I" instructions can be used in a constrained LR/SC loop.  This was always the case, but it was stated obliquely.
Resolves #1938

Clarify description of constrained LR/SC loops for Zca++

---

src/priv-preface.adoc
src/smstateen.adoc
src/supervisor.adoc

Since it was ratified as part of Ssqosid, there are actually no priv-1.14 changes in flight, so revert the version number to 1.13.

Rename mstateen0.P1P14 to mstateen0.SRMCFG

---

src/zc.adoc

The text refers to spimm as "the number of additional 16-byte address increments allocated for the stack frame." and "The total stack adjustment represents the total size of the stack frame, which is stack_adj_base added to spimm scaled by 16"
The "Example RV32I PUSH/POP sequences" section shows spimm with values of 0-3.
Based on the text and those examples, I think spimm is a 2-bit value rather than a 6-bit value.

Remove [5:4] after spimm in cm.push/pop wavedrom and assembly syntax explanation.

---

src/supervisor.adoc

Add missing SSE bit in senvcfg for RV32

---

src/v-st-ext.adoc

Clarify that vaadd intermediate results aren't truncated

---

src/c-st-ext.adoc
src/machine.adoc
src/zc.adoc

1. Invoking *ret from a too-low priv level results in illegal exception. This is otherwise not clearly stated.
2. Added clarifications around MISA.C and the D extension.
3. Rewrote a sentence discussing why we don't do load/store multiples in the C extension. See https://github.com/riscv/riscv-isa-manual/issues/1849 -- I think this will resolve that.

Three minor documentation tweaks

---

src/v-st-ext.adoc

In the fixed-point context, describing RDN as truncation is correct, since the effect of lopping off the LSBs is to round towards -inf for both unsigned and two's complement integers.
Because truncation effects a rounding towards zero in other number formats, including IEEE 754, truncation has become conflated with rounding towards zero.  (The terminology even shows up in the C standard.) This is unfortunate, but it is an avoidable source of confusion.

Avoid describing fixed-point RDN rounding mode as truncation

---

src/rnmi.adoc

mnepc is used by the MNRET instruction, not the MRET instruction.

Change reference in rnmi.adoc from MRET to MNRET

---

src/rvwmo.adoc

fixed missing frm reg in FCVT.W.D source registers

---

src/smstateen.adoc

For `mstateen*` and `hstateen*`, the spec states:
> For RV32, the registers listed above are 32-bit, and for the machine-level and
> hypervisor CSRs there is a corresponding set of high-half CSRs for the upper 32
> bits of each register
This is self-contradictory. If "the registers listed above are 32-bit", there are no "upper 32 bits" to access.
From the discussion in issue #1255, there is general agreement that CSRs that are defined as 64-bit and have "upper-half" analogues to be used for RV32 are indeed architecturally 64-bit.
Remove the assertion that the 64-bit registers are 32-bit for RV32.
(Also related to issue #1966.)

fix: mstateen*h and hstateen*h access upper half of 64-bit registers

---

src/c-st-ext.adoc

The C.ADD hints are split into unassigned ones where rs2≠x2-x5, and assigned ones where rs2=x2-x5, but the constraint was ≠ for both.

Fix constraint for assigned C.ADD hints

---

src/machine.adoc

XLEN can no longer be greater than MXLEN.
Resolves #2090

Remove now-impossible clause from PMP description

---

src/riscv-unprivileged.adoc

Presently, what should be Appendix C is included in Appendix B.
Fix this so have Appendices A, B, C, D.

Fix vector example appendix as separate from previous.

---

.github/workflows/merge-and-release.yml
Makefile
src/riscv-privileged.adoc
src/riscv-unprivileged.adoc

We now have three kinds of releases:
- Draft releases, which are the product of generating a copy of the spec from this repo on one's own machine.  These releases will include the DRAFT watermark and a note on the front page that says "DRAFT---NOT AN OFFICIAL RELEASE".
- Intermediate releases, which GitHub builds automatically when PRs are merged into the `main` branch of this repo.  The intent is that the `main` branch contains only ratified material, but since they are auto-generated, they aren't necessarily carefully vetted.  These releases will omit the DRAFT watermark but will include a note on the front page indicating they're "Intermediate" releases.
- Official releases, which are posted on `riscv.org` from time to time.  These omit the DRAFT watermark, obviously, and include a …

Mark GitHub-generated releases as "Intermediate Releases"

---

src/hypervisor.adoc

Following both the abbreviation itself, and the naming convention for medeleg/mideleg, hideleg should refer to interrupt delegation, not exception delegation which is already covered by hedeleg.

Fix copy/paste error, correcting hideleg to 'interrupt' rather than 'exception'.

---

src/v-st-ext.adoc

There are a handful of places in the vector ISA spec where we mandate illegal-instruction exceptions but really should have indicated the behavior is reserved. Implementations that raise illegal-instruction exceptions in these cases remain compatible, of course.

Fix some references to illegal-instruction exceptions that should be reserved

---

src/cmo.adoc

The behaviour can be technically inferred from this paragraph - as noted in one of the comments on that issue:
> Accessing the same location using different cacheability attributes may cause loss of coherence. Executing the following sequence between such accesses prevents both loss of coherence and loss of memory ordering: `fence iorw, iorw`, followed by `cbo.flush` to an address of that location, followed by a `fence iorw, iorw`.
However this is subtle, which means implementation bugs are likely. Making it explicit removes the risk of confusion and the resulting bugs.

Clarify interaction of CBOs and PBMTs

---

src/machine.adoc
src/supervisor.adoc

The behavior of a hardware-error exception is already described elsewhere in the text, but for clarity, we should mirror this subset of information in the mtval CSR description.

List hardware-error exceptions in relevant tval text

---

Makefile

Add hyperlinks in the Makefile output so you can easily ctrl-click the link to open the HTML/PDFs.

Add hyperlinks to Makefile output

---

src/scalar-crypto.adoc

Remove obsolete non-normative text in scalar crypto chapter

---

src/hypervisor.adoc

Avoid stating that the  G bit is reserved in the PTE of the G-stage address translation since the spec requires the G bit to be ignored.  Otherwise, we have a contradiction with an earlier section of the spec which states that a reserved bit in a PTE would lead to a page fault when such bit is set.

Avoid stating that G bit is reserved in PTE of G-stage

---

src/supervisor.adoc

A translation can indeed be satisfied by a cached translation from a different virtual-address width if there has been no intervening SFENCE.VMA

Clarify constrained-unpredictable translation rule wrt VA-width change

---

src/bfloat16.adoc
src/zfh.adoc

Using a single sentence to describe an extension-dependence relationship and an instruction-inclusion relationship is a source of confusion.
See https://github.com/riscv-software-src/riscv-isa-sim/pull/2058

Improve description of Zfbfmin extension

---

Makefile

The warning uses the `--recurse` flag but the actual command uses the `--recursive` flag.

Fix Makefile warning message for submodule checkout

---

Makefile

Adds a `DOCKER_BIN` variable that can be overridden to use `podman` instead of `docker`. The default is still docker, so there is no behavior change unless the variable is set.
Also update the docker volume suffixes for better SELinux support with podman (no change when using docker).

Update Makefile for better podman support

---

src/cmo.adoc

This is a clarification of the existing specified behavior, as interpreted in the (long) discussion at https://github.com/riscvarchive/riscv-CMOs/issues/73.  This PR copies https://github.com/riscvarchive/riscv-CMOs/pull/74 into `riscv-isa-manual`.
The concise text is from @gfavor. The expanded behavior it describes is:
> `menvcfg.CBIE` has no effect on the values read from the `henvcfg.CBIE` and `senvcfg.CBIE` fields.
> `menvcfg.CBCFE` has no effect on the values read from the `henvcfg.CBCFE` and `senvcfg.CBCFE` fields.
> `menvcfg.CBZE` has no effect on the values read from the `henvcfg.CBZE` and `senvcfg.CBZE` fields.
> 
> `henvcfg.CBIE` has no effect on the value read from the `senvcfg.CBIE` field.
> `henvcfg.CBCFE` has no effect on the value read from the `senvcfg.CBCFE` field.
> …

When menvcfg.* is 0, the henvcfg.* and senvcfg.* fields may still be written

---

src/scalar-crypto.adoc

This pre-dates integration into the ISA manual and doesn't look like a standard practice in the ISA manual.

Remove Changelog from Scalar Cryptography.

---

Makefile
normative_rule_defs/README.md
normative_rule_defs/m-st-ext.yaml
normative_rule_defs/machine.yaml
normative_rule_defs/rv-32-64g.yaml
normative_rule_defs/rv32.yaml
normative_rule_defs/rv64.yaml
normative_rule_defs/zilsd.yaml
src/colophon.adoc
src/m-st-ext.adoc
src/machine.adoc
src/rv-32-64g.adoc
src/rv32.adoc
src/rv64.adoc
src/zilsd.adoc
tagging_normative_rules.adoc

The ISA manual already has some of the normative rule tags in the adoc files (look for "norm:") but now I've added the ability to take those normative rule tags and then create a machine-readable list of normative rules. For each ISA manual adoc file, there will be a corresponding YAML file (in the top-level normative_rules_defs directory) that creates normative rules from the tags. The docs-resources repo has the required Ruby script to take all these input files (adoc and norm rule def files) and create a norm-rules.json output file. The docs-resources also has JSON schema files that define the format of the def files and the output file so you can get live schema checking of the defs YAML files if you use vscode to edit them. There are also documentation files (preliminary) that …

Add support for normative rule definitions to ISA manual - take 2

---

src/zc.adoc

"architecture class" -> "application class" to be consistent with other use of application class in this manual

Fixed typo of "architecture class"

---

src/v-st-ext.adoc

Remove the introductory note about the "currently frozen vector instructions" and the ratification process now that the vector extensions are ratified.

Remove freeze/ratification note from vector spec

---

src/zc.adoc

all the headings had : instead of ::

fix zcmp/zcmt instruction pages formatting

---

src/rv32.adoc
src/zc.adoc

Most were incorrectly marked as `sail`; one marked `text` is better annotated as `asm`.

Fix incorrect source language annotations.
